// Auto-generated list of Unicode emoji & symbol characters with names
// Generated from Unicode emoji/symbol blocks + custom symbol set

export const EMOJI_LIST = [
  { character: "★", name: "Black Star" },
  { character: "☆", name: "White Star" },
  { character: "♥", name: "Heart" },
  { character: "♡", name: "White Heart" },
  { character: "♦", name: "Diamond" },
  { character: "♠", name: "Spade" },
  { character: "♣", name: "Club" },
  { character: "☀", name: "Sun" },
  { character: "☁", name: "Cloud" },
  { character: "☂", name: "Umbrella" },
  { character: "✓", name: "Check Mark" },
  { character: "✗", name: "Cross Mark" },
  { character: "→", name: "Right Arrow" },
  { character: "←", name: "Left Arrow" },
  { character: "↑", name: "Up Arrow" },
  { character: "↓", name: "Down Arrow" },
  { character: "∞", name: "Infinity" },
  { character: "≈", name: "Approximately Equal" },
  { character: "≠", name: "Not Equal" },
  { character: "±", name: "Plus Minus" },
  { character: "×", name: "Multiplication" },
  { character: "÷", name: "Division" },
  { character: "√", name: "Square Root" },
  { character: "π", name: "Pi" },
  { character: "°", name: "Degree" },
  { character: "©", name: "Copyright" },
  { character: "®", name: "Registered" },
  { character: "™", name: "Trademark" },
  { character: "§", name: "Section" },
  { character: "¶", name: "Paragraph" },
  { character: "☃", name: "Snowman" },
  { character: "☄", name: "Comet" },
  { character: "☇", name: "Lightning" },
  { character: "☈", name: "Thunderstorm" },
  { character: "☉", name: "Sun" },
  { character: "☊", name: "Ascending Node" },
  { character: "☋", name: "Descending Node" },
  { character: "☌", name: "Conjunction" },
  { character: "☍", name: "Opposition" },
  { character: "☎", name: "Black Telephone" },
  { character: "☏", name: "White Telephone" },
  { character: "☐", name: "Ballot Box" },
  { character: "☑", name: "Ballot Box With Check" },
  { character: "☒", name: "Ballot Box With X" },
  { character: "☓", name: "Saltire" },
  { character: "☔", name: "Umbrella With Rain Drops" },
  { character: "☕", name: "Hot Beverage" },
  { character: "☖", name: "White Shogi Piece" },
  { character: "☗", name: "Black Shogi Piece" },
  { character: "☘", name: "Shamrock" },
  { character: "☙", name: "Reversed Rotated Floral Heart Bullet" },
  { character: "☚", name: "Black Left Pointing Index" },
  { character: "☛", name: "Black Right Pointing Index" },
  { character: "☜", name: "White Left Pointing Index" },
  { character: "☝", name: "White Up Pointing Index" },
  { character: "☞", name: "White Right Pointing Index" },
  { character: "☟", name: "White Down Pointing Index" },
  { character: "☠", name: "Skull And Crossbones" },
  { character: "☡", name: "Caution Sign" },
  { character: "☢", name: "Radioactive Sign" },
  { character: "☣", name: "Biohazard Sign" },
  { character: "☤", name: "Caduceus" },
  { character: "☥", name: "Ankh" },
  { character: "☦", name: "Orthodox Cross" },
  { character: "☧", name: "Chi Rho" },
  { character: "☨", name: "Cross Of Lorraine" },
  { character: "☩", name: "Cross Of Jerusalem" },
  { character: "☪", name: "Star And Crescent" },
  { character: "☫", name: "Farsi Symbol" },
  { character: "☬", name: "Adi Shakti" },
  { character: "☭", name: "Hammer And Sickle" },
  { character: "☮", name: "Peace Symbol" },
  { character: "☯", name: "Yin Yang" },
  { character: "☰", name: "Trigram For Heaven" },
  { character: "☱", name: "Trigram For Lake" },
  { character: "☲", name: "Trigram For Fire" },
  { character: "☳", name: "Trigram For Thunder" },
  { character: "☴", name: "Trigram For Wind" },
  { character: "☵", name: "Trigram For Water" },
  { character: "☶", name: "Trigram For Mountain" },
  { character: "☷", name: "Trigram For Earth" },
  { character: "☸", name: "Wheel Of Dharma" },
  { character: "☹", name: "White Frowning Face" },
  { character: "☺", name: "White Smiling Face" },
  { character: "☻", name: "Black Smiling Face" },
  { character: "☼", name: "White Sun With Rays" },
  { character: "☽", name: "First Quarter Moon" },
  { character: "☾", name: "Last Quarter Moon" },
  { character: "☿", name: "Mercury" },
  { character: "♀", name: "Female Sign" },
  { character: "♁", name: "Earth" },
  { character: "♂", name: "Male Sign" },
  { character: "♃", name: "Jupiter" },
  { character: "♄", name: "Saturn" },
  { character: "♅", name: "Uranus" },
  { character: "♆", name: "Neptune" },
  { character: "♇", name: "Pluto" },
  { character: "♈", name: "Aries" },
  { character: "♉", name: "Taurus" },
  { character: "♊", name: "Gemini" },
  { character: "♋", name: "Cancer" },
  { character: "♌", name: "Leo" },
  { character: "♍", name: "Virgo" },
  { character: "♎", name: "Libra" },
  { character: "♏", name: "Scorpius" },
  { character: "♐", name: "Sagittarius" },
  { character: "♑", name: "Capricorn" },
  { character: "♒", name: "Aquarius" },
  { character: "♓", name: "Pisces" },
  { character: "♔", name: "White Chess King" },
  { character: "♕", name: "White Chess Queen" },
  { character: "♖", name: "White Chess Rook" },
  { character: "♗", name: "White Chess Bishop" },
  { character: "♘", name: "White Chess Knight" },
  { character: "♙", name: "White Chess Pawn" },
  { character: "♚", name: "Black Chess King" },
  { character: "♛", name: "Black Chess Queen" },
  { character: "♜", name: "Black Chess Rook" },
  { character: "♝", name: "Black Chess Bishop" },
  { character: "♞", name: "Black Chess Knight" },
  { character: "♟", name: "Black Chess Pawn" },
  { character: "♢", name: "White Diamond Suit" },
  { character: "♤", name: "White Spade Suit" },
  { character: "♧", name: "White Club Suit" },
  { character: "♨", name: "Hot Springs" },
  { character: "♩", name: "Quarter Note" },
  { character: "♪", name: "Eighth Note" },
  { character: "♫", name: "Beamed Eighth Notes" },
  { character: "♬", name: "Beamed Sixteenth Notes" },
  { character: "♭", name: "Music Flat Sign" },
  { character: "♮", name: "Music Natural Sign" },
  { character: "♯", name: "Music Sharp Sign" },
  { character: "♰", name: "West Syriac Cross" },
  { character: "♱", name: "East Syriac Cross" },
  { character: "♲", name: "Universal Recycling Symbol" },
  { character: "♳", name: "Recycling Symbol For Type-1 Plastics" },
  { character: "♴", name: "Recycling Symbol For Type-2 Plastics" },
  { character: "♵", name: "Recycling Symbol For Type-3 Plastics" },
  { character: "♶", name: "Recycling Symbol For Type-4 Plastics" },
  { character: "♷", name: "Recycling Symbol For Type-5 Plastics" },
  { character: "♸", name: "Recycling Symbol For Type-6 Plastics" },
  { character: "♹", name: "Recycling Symbol For Type-7 Plastics" },
  { character: "♺", name: "Recycling Symbol For Generic Materials" },
  { character: "♻", name: "Black Universal Recycling Symbol" },
  { character: "♼", name: "Recycled Paper Symbol" },
  { character: "♽", name: "Partially-Recycled Paper Symbol" },
  { character: "♾", name: "Permanent Paper Sign" },
  { character: "♿", name: "Wheelchair Symbol" },
  { character: "⚀", name: "Die Face-1" },
  { character: "⚁", name: "Die Face-2" },
  { character: "⚂", name: "Die Face-3" },
  { character: "⚃", name: "Die Face-4" },
  { character: "⚄", name: "Die Face-5" },
  { character: "⚅", name: "Die Face-6" },
  { character: "⚆", name: "White Circle With Dot Right" },
  { character: "⚇", name: "White Circle With Two Dots" },
  { character: "⚈", name: "Black Circle With White Dot Right" },
  { character: "⚉", name: "Black Circle With Two White Dots" },
  { character: "⚊", name: "Monogram For Yang" },
  { character: "⚋", name: "Monogram For Yin" },
  { character: "⚌", name: "Digram For Greater Yang" },
  { character: "⚍", name: "Digram For Lesser Yin" },
  { character: "⚎", name: "Digram For Lesser Yang" },
  { character: "⚏", name: "Digram For Greater Yin" },
  { character: "⚐", name: "White Flag" },
  { character: "⚑", name: "Black Flag" },
  { character: "⚒", name: "Hammer And Pick" },
  { character: "⚓", name: "Anchor" },
  { character: "⚔", name: "Crossed Swords" },
  { character: "⚕", name: "Staff Of Aesculapius" },
  { character: "⚖", name: "Scales" },
  { character: "⚗", name: "Alembic" },
  { character: "⚘", name: "Flower" },
  { character: "⚙", name: "Gear" },
  { character: "⚚", name: "Staff Of Hermes" },
  { character: "⚛", name: "Atom Symbol" },
  { character: "⚜", name: "Fleur-De-Lis" },
  { character: "⚝", name: "Outlined White Star" },
  { character: "⚞", name: "Three Lines Converging Right" },
  { character: "⚟", name: "Three Lines Converging Left" },
  { character: "⚠", name: "Warning Sign" },
  { character: "⚡", name: "High Voltage Sign" },
  { character: "⚢", name: "Doubled Female Sign" },
  { character: "⚣", name: "Doubled Male Sign" },
  { character: "⚤", name: "Interlocked Female And Male Sign" },
  { character: "⚥", name: "Male And Female Sign" },
  { character: "⚦", name: "Male With Stroke Sign" },
  { character: "⚧", name: "Male With Stroke And Male And Female Sign" },
  { character: "⚨", name: "Vertical Male With Stroke Sign" },
  { character: "⚩", name: "Horizontal Male With Stroke Sign" },
  { character: "⚪", name: "Medium White Circle" },
  { character: "⚫", name: "Medium Black Circle" },
  { character: "⚬", name: "Medium Small White Circle" },
  { character: "⚭", name: "Marriage Symbol" },
  { character: "⚮", name: "Divorce Symbol" },
  { character: "⚯", name: "Unmarried Partnership Symbol" },
  { character: "⚰", name: "Coffin" },
  { character: "⚱", name: "Funeral Urn" },
  { character: "⚲", name: "Neuter" },
  { character: "⚳", name: "Ceres" },
  { character: "⚴", name: "Pallas" },
  { character: "⚵", name: "Juno" },
  { character: "⚶", name: "Vesta" },
  { character: "⚷", name: "Chiron" },
  { character: "⚸", name: "Black Moon Lilith" },
  { character: "⚹", name: "Sextile" },
  { character: "⚺", name: "Semisextile" },
  { character: "⚻", name: "Quincunx" },
  { character: "⚼", name: "Sesquiquadrate" },
  { character: "⚽", name: "Soccer Ball" },
  { character: "⚾", name: "Baseball" },
  { character: "⚿", name: "Squared Key" },
  { character: "⛀", name: "White Draughts Man" },
  { character: "⛁", name: "White Draughts King" },
  { character: "⛂", name: "Black Draughts Man" },
  { character: "⛃", name: "Black Draughts King" },
  { character: "⛄", name: "Snowman Without Snow" },
  { character: "⛅", name: "Sun Behind Cloud" },
  { character: "⛆", name: "Rain" },
  { character: "⛇", name: "Black Snowman" },
  { character: "⛈", name: "Thunder Cloud And Rain" },
  { character: "⛉", name: "Turned White Shogi Piece" },
  { character: "⛊", name: "Turned Black Shogi Piece" },
  { character: "⛋", name: "White Diamond In Square" },
  { character: "⛌", name: "Crossing Lanes" },
  { character: "⛍", name: "Disabled Car" },
  { character: "⛎", name: "Ophiuchus" },
  { character: "⛏", name: "Pick" },
  { character: "⛐", name: "Car Sliding" },
  { character: "⛑", name: "Helmet With White Cross" },
  { character: "⛒", name: "Circled Crossing Lanes" },
  { character: "⛓", name: "Chains" },
  { character: "⛔", name: "No Entry" },
  { character: "⛕", name: "Alternate One-Way Left Way Traffic" },
  { character: "⛖", name: "Black Two-Way Left Way Traffic" },
  { character: "⛗", name: "White Two-Way Left Way Traffic" },
  { character: "⛘", name: "Black Left Lane Merge" },
  { character: "⛙", name: "White Left Lane Merge" },
  { character: "⛚", name: "Drive Slow Sign" },
  { character: "⛛", name: "Heavy White Down-Pointing Triangle" },
  { character: "⛜", name: "Left Closed Entry" },
  { character: "⛝", name: "Squared Saltire" },
  { character: "⛞", name: "Falling Diagonal In White Circle In Black Square" },
  { character: "⛟", name: "Black Truck" },
  { character: "⛠", name: "Restricted Left Entry-1" },
  { character: "⛡", name: "Restricted Left Entry-2" },
  { character: "⛢", name: "Astronomical Symbol For Uranus" },
  { character: "⛣", name: "Heavy Circle With Stroke And Two Dots Above" },
  { character: "⛤", name: "Pentagram" },
  { character: "⛥", name: "Right-Handed Interlaced Pentagram" },
  { character: "⛦", name: "Left-Handed Interlaced Pentagram" },
  { character: "⛧", name: "Inverted Pentagram" },
  { character: "⛨", name: "Black Cross On Shield" },
  { character: "⛩", name: "Shinto Shrine" },
  { character: "⛪", name: "Church" },
  { character: "⛫", name: "Castle" },
  { character: "⛬", name: "Historic Site" },
  { character: "⛭", name: "Gear Without Hub" },
  { character: "⛮", name: "Gear With Handles" },
  { character: "⛯", name: "Map Symbol For Lighthouse" },
  { character: "⛰", name: "Mountain" },
  { character: "⛱", name: "Umbrella On Ground" },
  { character: "⛲", name: "Fountain" },
  { character: "⛳", name: "Flag In Hole" },
  { character: "⛴", name: "Ferry" },
  { character: "⛵", name: "Sailboat" },
  { character: "⛶", name: "Square Four Corners" },
  { character: "⛷", name: "Skier" },
  { character: "⛸", name: "Ice Skate" },
  { character: "⛹", name: "Person With Ball" },
  { character: "⛺", name: "Tent" },
  { character: "⛻", name: "Japanese Bank Symbol" },
  { character: "⛼", name: "Headstone Graveyard Symbol" },
  { character: "⛽", name: "Fuel Pump" },
  { character: "⛾", name: "Cup On Black Square" },
  { character: "⛿", name: "White Flag With Horizontal Middle Black Stripe" },
  { character: "✀", name: "Black Safety Scissors" },
  { character: "✁", name: "Upper Blade Scissors" },
  { character: "✂", name: "Black Scissors" },
  { character: "✃", name: "Lower Blade Scissors" },
  { character: "✄", name: "White Scissors" },
  { character: "✅", name: "White Heavy Check Mark" },
  { character: "✆", name: "Telephone Location Sign" },
  { character: "✇", name: "Tape Drive" },
  { character: "✈", name: "Airplane" },
  { character: "✉", name: "Envelope" },
  { character: "✊", name: "Raised Fist" },
  { character: "✋", name: "Raised Hand" },
  { character: "✌", name: "Victory Hand" },
  { character: "✍", name: "Writing Hand" },
  { character: "✎", name: "Lower Right Pencil" },
  { character: "✏", name: "Pencil" },
  { character: "✐", name: "Upper Right Pencil" },
  { character: "✑", name: "White Nib" },
  { character: "✒", name: "Black Nib" },
  { character: "✔", name: "Heavy Check Mark" },
  { character: "✕", name: "Multiplication X" },
  { character: "✖", name: "Heavy Multiplication X" },
  { character: "✘", name: "Heavy Ballot X" },
  { character: "✙", name: "Outlined Greek Cross" },
  { character: "✚", name: "Heavy Greek Cross" },
  { character: "✛", name: "Open Centre Cross" },
  { character: "✜", name: "Heavy Open Centre Cross" },
  { character: "✝", name: "Latin Cross" },
  { character: "✞", name: "Shadowed White Latin Cross" },
  { character: "✟", name: "Outlined Latin Cross" },
  { character: "✠", name: "Maltese Cross" },
  { character: "✡", name: "Star Of David" },
  { character: "✢", name: "Four Teardrop-Spoked Asterisk" },
  { character: "✣", name: "Four Balloon-Spoked Asterisk" },
  { character: "✤", name: "Heavy Four Balloon-Spoked Asterisk" },
  { character: "✥", name: "Four Club-Spoked Asterisk" },
  { character: "✦", name: "Black Four Pointed Star" },
  { character: "✧", name: "White Four Pointed Star" },
  { character: "✨", name: "Sparkles" },
  { character: "✩", name: "Stress Outlined White Star" },
  { character: "✪", name: "Circled White Star" },
  { character: "✫", name: "Open Centre Black Star" },
  { character: "✬", name: "Black Centre White Star" },
  { character: "✭", name: "Outlined Black Star" },
  { character: "✮", name: "Heavy Outlined Black Star" },
  { character: "✯", name: "Pinwheel Star" },
  { character: "✰", name: "Shadowed White Star" },
  { character: "✱", name: "Heavy Asterisk" },
  { character: "✲", name: "Open Centre Asterisk" },
  { character: "✳", name: "Eight Spoked Asterisk" },
  { character: "✴", name: "Eight Pointed Black Star" },
  { character: "✵", name: "Eight Pointed Pinwheel Star" },
  { character: "✶", name: "Six Pointed Black Star" },
  { character: "✷", name: "Eight Pointed Rectilinear Black Star" },
  { character: "✸", name: "Heavy Eight Pointed Rectilinear Black Star" },
  { character: "✹", name: "Twelve Pointed Black Star" },
  { character: "✺", name: "Sixteen Pointed Asterisk" },
  { character: "✻", name: "Teardrop-Spoked Asterisk" },
  { character: "✼", name: "Open Centre Teardrop-Spoked Asterisk" },
  { character: "✽", name: "Heavy Teardrop-Spoked Asterisk" },
  { character: "✾", name: "Six Petalled Black And White Florette" },
  { character: "✿", name: "Black Florette" },
  { character: "❀", name: "White Florette" },
  { character: "❁", name: "Eight Petalled Outlined Black Florette" },
  { character: "❂", name: "Circled Open Centre Eight Pointed Star" },
  { character: "❃", name: "Heavy Teardrop-Spoked Pinwheel Asterisk" },
  { character: "❄", name: "Snowflake" },
  { character: "❅", name: "Tight Trifoliate Snowflake" },
  { character: "❆", name: "Heavy Chevron Snowflake" },
  { character: "❇", name: "Sparkle" },
  { character: "❈", name: "Heavy Sparkle" },
  { character: "❉", name: "Balloon-Spoked Asterisk" },
  { character: "❊", name: "Eight Teardrop-Spoked Propeller Asterisk" },
  { character: "❋", name: "Heavy Eight Teardrop-Spoked Propeller Asterisk" },
  { character: "❌", name: "Cross Mark" },
  { character: "❍", name: "Shadowed White Circle" },
  { character: "❎", name: "Negative Squared Cross Mark" },
  { character: "❏", name: "Lower Right Drop-Shadowed White Square" },
  { character: "❐", name: "Upper Right Drop-Shadowed White Square" },
  { character: "❑", name: "Lower Right Shadowed White Square" },
  { character: "❒", name: "Upper Right Shadowed White Square" },
  { character: "❓", name: "Black Question Mark Ornament" },
  { character: "❔", name: "White Question Mark Ornament" },
  { character: "❕", name: "White Exclamation Mark Ornament" },
  { character: "❖", name: "Black Diamond Minus White X" },
  { character: "❗", name: "Heavy Exclamation Mark Symbol" },
  { character: "❘", name: "Light Vertical Bar" },
  { character: "❙", name: "Medium Vertical Bar" },
  { character: "❚", name: "Heavy Vertical Bar" },
  { character: "❛", name: "Heavy Single Turned Comma Quotation Mark Ornament" },
  { character: "❜", name: "Heavy Single Comma Quotation Mark Ornament" },
  { character: "❝", name: "Heavy Double Turned Comma Quotation Mark Ornament" },
  { character: "❞", name: "Heavy Double Comma Quotation Mark Ornament" },
  { character: "❟", name: "Heavy Low Single Comma Quotation Mark Ornament" },
  { character: "❠", name: "Heavy Low Double Comma Quotation Mark Ornament" },
  { character: "❡", name: "Curved Stem Paragraph Sign Ornament" },
  { character: "❢", name: "Heavy Exclamation Mark Ornament" },
  { character: "❣", name: "Heavy Heart Exclamation Mark Ornament" },
  { character: "❤", name: "Heavy Black Heart" },
  { character: "❥", name: "Rotated Heavy Black Heart Bullet" },
  { character: "❦", name: "Floral Heart" },
  { character: "❧", name: "Rotated Floral Heart Bullet" },
  { character: "❨", name: "Medium Left Parenthesis Ornament" },
  { character: "❩", name: "Medium Right Parenthesis Ornament" },
  { character: "❪", name: "Medium Flattened Left Parenthesis Ornament" },
  { character: "❫", name: "Medium Flattened Right Parenthesis Ornament" },
  { character: "❬", name: "Medium Left-Pointing Angle Bracket Ornament" },
  { character: "❭", name: "Medium Right-Pointing Angle Bracket Ornament" },
  { character: "❮", name: "Heavy Left-Pointing Angle Quotation Mark Ornament" },
  { character: "❯", name: "Heavy Right-Pointing Angle Quotation Mark Ornament" },
  { character: "❰", name: "Heavy Left-Pointing Angle Bracket Ornament" },
  { character: "❱", name: "Heavy Right-Pointing Angle Bracket Ornament" },
  { character: "❲", name: "Light Left Tortoise Shell Bracket Ornament" },
  { character: "❳", name: "Light Right Tortoise Shell Bracket Ornament" },
  { character: "❴", name: "Medium Left Curly Bracket Ornament" },
  { character: "❵", name: "Medium Right Curly Bracket Ornament" },
  { character: "❶", name: "Dingbat Negative Circled Digit One" },
  { character: "❷", name: "Dingbat Negative Circled Digit Two" },
  { character: "❸", name: "Dingbat Negative Circled Digit Three" },
  { character: "❹", name: "Dingbat Negative Circled Digit Four" },
  { character: "❺", name: "Dingbat Negative Circled Digit Five" },
  { character: "❻", name: "Dingbat Negative Circled Digit Six" },
  { character: "❼", name: "Dingbat Negative Circled Digit Seven" },
  { character: "❽", name: "Dingbat Negative Circled Digit Eight" },
  { character: "❾", name: "Dingbat Negative Circled Digit Nine" },
  { character: "❿", name: "Dingbat Negative Circled Number Ten" },
  { character: "➀", name: "Dingbat Circled Sans-Serif Digit One" },
  { character: "➁", name: "Dingbat Circled Sans-Serif Digit Two" },
  { character: "➂", name: "Dingbat Circled Sans-Serif Digit Three" },
  { character: "➃", name: "Dingbat Circled Sans-Serif Digit Four" },
  { character: "➄", name: "Dingbat Circled Sans-Serif Digit Five" },
  { character: "➅", name: "Dingbat Circled Sans-Serif Digit Six" },
  { character: "➆", name: "Dingbat Circled Sans-Serif Digit Seven" },
  { character: "➇", name: "Dingbat Circled Sans-Serif Digit Eight" },
  { character: "➈", name: "Dingbat Circled Sans-Serif Digit Nine" },
  { character: "➉", name: "Dingbat Circled Sans-Serif Number Ten" },
  { character: "➊", name: "Dingbat Negative Circled Sans-Serif Digit One" },
  { character: "➋", name: "Dingbat Negative Circled Sans-Serif Digit Two" },
  { character: "➌", name: "Dingbat Negative Circled Sans-Serif Digit Three" },
  { character: "➍", name: "Dingbat Negative Circled Sans-Serif Digit Four" },
  { character: "➎", name: "Dingbat Negative Circled Sans-Serif Digit Five" },
  { character: "➏", name: "Dingbat Negative Circled Sans-Serif Digit Six" },
  { character: "➐", name: "Dingbat Negative Circled Sans-Serif Digit Seven" },
  { character: "➑", name: "Dingbat Negative Circled Sans-Serif Digit Eight" },
  { character: "➒", name: "Dingbat Negative Circled Sans-Serif Digit Nine" },
  { character: "➓", name: "Dingbat Negative Circled Sans-Serif Number Ten" },
  { character: "➔", name: "Heavy Wide-Headed Rightwards Arrow" },
  { character: "➕", name: "Heavy Plus Sign" },
  { character: "➖", name: "Heavy Minus Sign" },
  { character: "➗", name: "Heavy Division Sign" },
  { character: "➘", name: "Heavy South East Arrow" },
  { character: "➙", name: "Heavy Rightwards Arrow" },
  { character: "➚", name: "Heavy North East Arrow" },
  { character: "➛", name: "Drafting Point Rightwards Arrow" },
  { character: "➜", name: "Heavy Round-Tipped Rightwards Arrow" },
  { character: "➝", name: "Triangle-Headed Rightwards Arrow" },
  { character: "➞", name: "Heavy Triangle-Headed Rightwards Arrow" },
  { character: "➟", name: "Dashed Triangle-Headed Rightwards Arrow" },
  { character: "➠", name: "Heavy Dashed Triangle-Headed Rightwards Arrow" },
  { character: "➡", name: "Black Rightwards Arrow" },
  { character: "➢", name: "Three-D Top-Lighted Rightwards Arrowhead" },
  { character: "➣", name: "Three-D Bottom-Lighted Rightwards Arrowhead" },
  { character: "➤", name: "Black Rightwards Arrowhead" },
  { character: "➥", name: "Heavy Black Curved Downwards And Rightwards Arrow" },
  { character: "➦", name: "Heavy Black Curved Upwards And Rightwards Arrow" },
  { character: "➧", name: "Squat Black Rightwards Arrow" },
  { character: "➨", name: "Heavy Concave-Pointed Black Rightwards Arrow" },
  { character: "➩", name: "Right-Shaded White Rightwards Arrow" },
  { character: "➪", name: "Left-Shaded White Rightwards Arrow" },
  { character: "➫", name: "Back-Tilted Shadowed White Rightwards Arrow" },
  { character: "➬", name: "Front-Tilted Shadowed White Rightwards Arrow" },
  { character: "➭", name: "Heavy Lower Right-Shadowed White Rightwards Arrow" },
  { character: "➮", name: "Heavy Upper Right-Shadowed White Rightwards Arrow" },
  { character: "➯", name: "Notched Lower Right-Shadowed White Rightwards Arrow" },
  { character: "➰", name: "Curly Loop" },
  { character: "➱", name: "Notched Upper Right-Shadowed White Rightwards Arrow" },
  { character: "➲", name: "Circled Heavy White Rightwards Arrow" },
  { character: "➳", name: "White-Feathered Rightwards Arrow" },
  { character: "➴", name: "Black-Feathered South East Arrow" },
  { character: "➵", name: "Black-Feathered Rightwards Arrow" },
  { character: "➶", name: "Black-Feathered North East Arrow" },
  { character: "➷", name: "Heavy Black-Feathered South East Arrow" },
  { character: "➸", name: "Heavy Black-Feathered Rightwards Arrow" },
  { character: "➹", name: "Heavy Black-Feathered North East Arrow" },
  { character: "➺", name: "Teardrop-Barbed Rightwards Arrow" },
  { character: "➻", name: "Heavy Teardrop-Shanked Rightwards Arrow" },
  { character: "➼", name: "Wedge-Tailed Rightwards Arrow" },
  { character: "➽", name: "Heavy Wedge-Tailed Rightwards Arrow" },
  { character: "➾", name: "Open-Outlined Rightwards Arrow" },
  { character: "➿", name: "Double Curly Loop" },
  { character: "🌀", name: "Cyclone" },
  { character: "🌁", name: "Foggy" },
  { character: "🌂", name: "Closed Umbrella" },
  { character: "🌃", name: "Night With Stars" },
  { character: "🌄", name: "Sunrise Over Mountains" },
  { character: "🌅", name: "Sunrise" },
  { character: "🌆", name: "Cityscape At Dusk" },
  { character: "🌇", name: "Sunset Over Buildings" },
  { character: "🌈", name: "Rainbow" },
  { character: "🌉", name: "Bridge At Night" },
  { character: "🌊", name: "Water Wave" },
  { character: "🌋", name: "Volcano" },
  { character: "🌌", name: "Milky Way" },
  { character: "🌍", name: "Earth Globe Europe-Africa" },
  { character: "🌎", name: "Earth Globe Americas" },
  { character: "🌏", name: "Earth Globe Asia-Australia" },
  { character: "🌐", name: "Globe With Meridians" },
  { character: "🌑", name: "New Moon Symbol" },
  { character: "🌒", name: "Waxing Crescent Moon Symbol" },
  { character: "🌓", name: "First Quarter Moon Symbol" },
  { character: "🌔", name: "Waxing Gibbous Moon Symbol" },
  { character: "🌕", name: "Full Moon Symbol" },
  { character: "🌖", name: "Waning Gibbous Moon Symbol" },
  { character: "🌗", name: "Last Quarter Moon Symbol" },
  { character: "🌘", name: "Waning Crescent Moon Symbol" },
  { character: "🌙", name: "Crescent Moon" },
  { character: "🌚", name: "New Moon With Face" },
  { character: "🌛", name: "First Quarter Moon With Face" },
  { character: "🌜", name: "Last Quarter Moon With Face" },
  { character: "🌝", name: "Full Moon With Face" },
  { character: "🌞", name: "Sun With Face" },
  { character: "🌟", name: "Glowing Star" },
  { character: "🌠", name: "Shooting Star" },
  { character: "🌡", name: "Thermometer" },
  { character: "🌢", name: "Black Droplet" },
  { character: "🌣", name: "White Sun" },
  { character: "🌤", name: "White Sun With Small Cloud" },
  { character: "🌥", name: "White Sun Behind Cloud" },
  { character: "🌦", name: "White Sun Behind Cloud With Rain" },
  { character: "🌧", name: "Cloud With Rain" },
  { character: "🌨", name: "Cloud With Snow" },
  { character: "🌩", name: "Cloud With Lightning" },
  { character: "🌪", name: "Cloud With Tornado" },
  { character: "🌫", name: "Fog" },
  { character: "🌬", name: "Wind Blowing Face" },
  { character: "🌭", name: "Hot Dog" },
  { character: "🌮", name: "Taco" },
  { character: "🌯", name: "Burrito" },
  { character: "🌰", name: "Chestnut" },
  { character: "🌱", name: "Seedling" },
  { character: "🌲", name: "Evergreen Tree" },
  { character: "🌳", name: "Deciduous Tree" },
  { character: "🌴", name: "Palm Tree" },
  { character: "🌵", name: "Cactus" },
  { character: "🌶", name: "Hot Pepper" },
  { character: "🌷", name: "Tulip" },
  { character: "🌸", name: "Cherry Blossom" },
  { character: "🌹", name: "Rose" },
  { character: "🌺", name: "Hibiscus" },
  { character: "🌻", name: "Sunflower" },
  { character: "🌼", name: "Blossom" },
  { character: "🌽", name: "Ear Of Maize" },
  { character: "🌾", name: "Ear Of Rice" },
  { character: "🌿", name: "Herb" },
  { character: "🍀", name: "Four Leaf Clover" },
  { character: "🍁", name: "Maple Leaf" },
  { character: "🍂", name: "Fallen Leaf" },
  { character: "🍃", name: "Leaf Fluttering In Wind" },
  { character: "🍄", name: "Mushroom" },
  { character: "🍅", name: "Tomato" },
  { character: "🍆", name: "Aubergine" },
  { character: "🍇", name: "Grapes" },
  { character: "🍈", name: "Melon" },
  { character: "🍉", name: "Watermelon" },
  { character: "🍊", name: "Tangerine" },
  { character: "🍋", name: "Lemon" },
  { character: "🍌", name: "Banana" },
  { character: "🍍", name: "Pineapple" },
  { character: "🍎", name: "Red Apple" },
  { character: "🍏", name: "Green Apple" },
  { character: "🍐", name: "Pear" },
  { character: "🍑", name: "Peach" },
  { character: "🍒", name: "Cherries" },
  { character: "🍓", name: "Strawberry" },
  { character: "🍔", name: "Hamburger" },
  { character: "🍕", name: "Slice Of Pizza" },
  { character: "🍖", name: "Meat On Bone" },
  { character: "🍗", name: "Poultry Leg" },
  { character: "🍘", name: "Rice Cracker" },
  { character: "🍙", name: "Rice Ball" },
  { character: "🍚", name: "Cooked Rice" },
  { character: "🍛", name: "Curry And Rice" },
  { character: "🍜", name: "Steaming Bowl" },
  { character: "🍝", name: "Spaghetti" },
  { character: "🍞", name: "Bread" },
  { character: "🍟", name: "French Fries" },
  { character: "🍠", name: "Roasted Sweet Potato" },
  { character: "🍡", name: "Dango" },
  { character: "🍢", name: "Oden" },
  { character: "🍣", name: "Sushi" },
  { character: "🍤", name: "Fried Shrimp" },
  { character: "🍥", name: "Fish Cake With Swirl Design" },
  { character: "🍦", name: "Soft Ice Cream" },
  { character: "🍧", name: "Shaved Ice" },
  { character: "🍨", name: "Ice Cream" },
  { character: "🍩", name: "Doughnut" },
  { character: "🍪", name: "Cookie" },
  { character: "🍫", name: "Chocolate Bar" },
  { character: "🍬", name: "Candy" },
  { character: "🍭", name: "Lollipop" },
  { character: "🍮", name: "Custard" },
  { character: "🍯", name: "Honey Pot" },
  { character: "🍰", name: "Shortcake" },
  { character: "🍱", name: "Bento Box" },
  { character: "🍲", name: "Pot Of Food" },
  { character: "🍳", name: "Cooking" },
  { character: "🍴", name: "Fork And Knife" },
  { character: "🍵", name: "Teacup Without Handle" },
  { character: "🍶", name: "Sake Bottle And Cup" },
  { character: "🍷", name: "Wine Glass" },
  { character: "🍸", name: "Cocktail Glass" },
  { character: "🍹", name: "Tropical Drink" },
  { character: "🍺", name: "Beer Mug" },
  { character: "🍻", name: "Clinking Beer Mugs" },
  { character: "🍼", name: "Baby Bottle" },
  { character: "🍽", name: "Fork And Knife With Plate" },
  { character: "🍾", name: "Bottle With Popping Cork" },
  { character: "🍿", name: "Popcorn" },
  { character: "🎀", name: "Ribbon" },
  { character: "🎁", name: "Wrapped Present" },
  { character: "🎂", name: "Birthday Cake" },
  { character: "🎃", name: "Jack-O-Lantern" },
  { character: "🎄", name: "Christmas Tree" },
  { character: "🎅", name: "Father Christmas" },
  { character: "🎆", name: "Fireworks" },
  { character: "🎇", name: "Firework Sparkler" },
  { character: "🎈", name: "Balloon" },
  { character: "🎉", name: "Party Popper" },
  { character: "🎊", name: "Confetti Ball" },
  { character: "🎋", name: "Tanabata Tree" },
  { character: "🎌", name: "Crossed Flags" },
  { character: "🎍", name: "Pine Decoration" },
  { character: "🎎", name: "Japanese Dolls" },
  { character: "🎏", name: "Carp Streamer" },
  { character: "🎐", name: "Wind Chime" },
  { character: "🎑", name: "Moon Viewing Ceremony" },
  { character: "🎒", name: "School Satchel" },
  { character: "🎓", name: "Graduation Cap" },
  { character: "🎔", name: "Heart With Tip On The Left" },
  { character: "🎕", name: "Bouquet Of Flowers" },
  { character: "🎖", name: "Military Medal" },
  { character: "🎗", name: "Reminder Ribbon" },
  { character: "🎘", name: "Musical Keyboard With Jacks" },
  { character: "🎙", name: "Studio Microphone" },
  { character: "🎚", name: "Level Slider" },
  { character: "🎛", name: "Control Knobs" },
  { character: "🎜", name: "Beamed Ascending Musical Notes" },
  { character: "🎝", name: "Beamed Descending Musical Notes" },
  { character: "🎞", name: "Film Frames" },
  { character: "🎟", name: "Admission Tickets" },
  { character: "🎠", name: "Carousel Horse" },
  { character: "🎡", name: "Ferris Wheel" },
  { character: "🎢", name: "Roller Coaster" },
  { character: "🎣", name: "Fishing Pole And Fish" },
  { character: "🎤", name: "Microphone" },
  { character: "🎥", name: "Movie Camera" },
  { character: "🎦", name: "Cinema" },
  { character: "🎧", name: "Headphone" },
  { character: "🎨", name: "Artist Palette" },
  { character: "🎩", name: "Top Hat" },
  { character: "🎪", name: "Circus Tent" },
  { character: "🎫", name: "Ticket" },
  { character: "🎬", name: "Clapper Board" },
  { character: "🎭", name: "Performing Arts" },
  { character: "🎮", name: "Video Game" },
  { character: "🎯", name: "Direct Hit" },
  { character: "🎰", name: "Slot Machine" },
  { character: "🎱", name: "Billiards" },
  { character: "🎲", name: "Game Die" },
  { character: "🎳", name: "Bowling" },
  { character: "🎴", name: "Flower Playing Cards" },
  { character: "🎵", name: "Musical Note" },
  { character: "🎶", name: "Multiple Musical Notes" },
  { character: "🎷", name: "Saxophone" },
  { character: "🎸", name: "Guitar" },
  { character: "🎹", name: "Musical Keyboard" },
  { character: "🎺", name: "Trumpet" },
  { character: "🎻", name: "Violin" },
  { character: "🎼", name: "Musical Score" },
  { character: "🎽", name: "Running Shirt With Sash" },
  { character: "🎾", name: "Tennis Racquet And Ball" },
  { character: "🎿", name: "Ski And Ski Boot" },
  { character: "🏀", name: "Basketball And Hoop" },
  { character: "🏁", name: "Chequered Flag" },
  { character: "🏂", name: "Snowboarder" },
  { character: "🏃", name: "Runner" },
  { character: "🏄", name: "Surfer" },
  { character: "🏅", name: "Sports Medal" },
  { character: "🏆", name: "Trophy" },
  { character: "🏇", name: "Horse Racing" },
  { character: "🏈", name: "American Football" },
  { character: "🏉", name: "Rugby Football" },
  { character: "🏊", name: "Swimmer" },
  { character: "🏋", name: "Weight Lifter" },
  { character: "🏌", name: "Golfer" },
  { character: "🏍", name: "Racing Motorcycle" },
  { character: "🏎", name: "Racing Car" },
  { character: "🏏", name: "Cricket Bat And Ball" },
  { character: "🏐", name: "Volleyball" },
  { character: "🏑", name: "Field Hockey Stick And Ball" },
  { character: "🏒", name: "Ice Hockey Stick And Puck" },
  { character: "🏓", name: "Table Tennis Paddle And Ball" },
  { character: "🏔", name: "Snow Capped Mountain" },
  { character: "🏕", name: "Camping" },
  { character: "🏖", name: "Beach With Umbrella" },
  { character: "🏗", name: "Building Construction" },
  { character: "🏘", name: "House Buildings" },
  { character: "🏙", name: "Cityscape" },
  { character: "🏚", name: "Derelict House Building" },
  { character: "🏛", name: "Classical Building" },
  { character: "🏜", name: "Desert" },
  { character: "🏝", name: "Desert Island" },
  { character: "🏞", name: "National Park" },
  { character: "🏟", name: "Stadium" },
  { character: "🏠", name: "House Building" },
  { character: "🏡", name: "House With Garden" },
  { character: "🏢", name: "Office Building" },
  { character: "🏣", name: "Japanese Post Office" },
  { character: "🏤", name: "European Post Office" },
  { character: "🏥", name: "Hospital" },
  { character: "🏦", name: "Bank" },
  { character: "🏧", name: "Automated Teller Machine" },
  { character: "🏨", name: "Hotel" },
  { character: "🏩", name: "Love Hotel" },
  { character: "🏪", name: "Convenience Store" },
  { character: "🏫", name: "School" },
  { character: "🏬", name: "Department Store" },
  { character: "🏭", name: "Factory" },
  { character: "🏮", name: "Izakaya Lantern" },
  { character: "🏯", name: "Japanese Castle" },
  { character: "🏰", name: "European Castle" },
  { character: "🏱", name: "White Pennant" },
  { character: "🏲", name: "Black Pennant" },
  { character: "🏳", name: "Waving White Flag" },
  { character: "🏴", name: "Waving Black Flag" },
  { character: "🏵", name: "Rosette" },
  { character: "🏶", name: "Black Rosette" },
  { character: "🏷", name: "Label" },
  { character: "🏸", name: "Badminton Racquet And Shuttlecock" },
  { character: "🏹", name: "Bow And Arrow" },
  { character: "🏺", name: "Amphora" },
  { character: "🏻", name: "Emoji Modifier Fitzpatrick Type-1-2" },
  { character: "🏼", name: "Emoji Modifier Fitzpatrick Type-3" },
  { character: "🏽", name: "Emoji Modifier Fitzpatrick Type-4" },
  { character: "🏾", name: "Emoji Modifier Fitzpatrick Type-5" },
  { character: "🏿", name: "Emoji Modifier Fitzpatrick Type-6" },
  { character: "🐀", name: "Rat" },
  { character: "🐁", name: "Mouse" },
  { character: "🐂", name: "Ox" },
  { character: "🐃", name: "Water Buffalo" },
  { character: "🐄", name: "Cow" },
  { character: "🐅", name: "Tiger" },
  { character: "🐆", name: "Leopard" },
  { character: "🐇", name: "Rabbit" },
  { character: "🐈", name: "Cat" },
  { character: "🐉", name: "Dragon" },
  { character: "🐊", name: "Crocodile" },
  { character: "🐋", name: "Whale" },
  { character: "🐌", name: "Snail" },
  { character: "🐍", name: "Snake" },
  { character: "🐎", name: "Horse" },
  { character: "🐏", name: "Ram" },
  { character: "🐐", name: "Goat" },
  { character: "🐑", name: "Sheep" },
  { character: "🐒", name: "Monkey" },
  { character: "🐓", name: "Rooster" },
  { character: "🐔", name: "Chicken" },
  { character: "🐕", name: "Dog" },
  { character: "🐖", name: "Pig" },
  { character: "🐗", name: "Boar" },
  { character: "🐘", name: "Elephant" },
  { character: "🐙", name: "Octopus" },
  { character: "🐚", name: "Spiral Shell" },
  { character: "🐛", name: "Bug" },
  { character: "🐜", name: "Ant" },
  { character: "🐝", name: "Honeybee" },
  { character: "🐞", name: "Lady Beetle" },
  { character: "🐟", name: "Fish" },
  { character: "🐠", name: "Tropical Fish" },
  { character: "🐡", name: "Blowfish" },
  { character: "🐢", name: "Turtle" },
  { character: "🐣", name: "Hatching Chick" },
  { character: "🐤", name: "Baby Chick" },
  { character: "🐥", name: "Front-Facing Baby Chick" },
  { character: "🐦", name: "Bird" },
  { character: "🐧", name: "Penguin" },
  { character: "🐨", name: "Koala" },
  { character: "🐩", name: "Poodle" },
  { character: "🐪", name: "Dromedary Camel" },
  { character: "🐫", name: "Bactrian Camel" },
  { character: "🐬", name: "Dolphin" },
  { character: "🐭", name: "Mouse Face" },
  { character: "🐮", name: "Cow Face" },
  { character: "🐯", name: "Tiger Face" },
  { character: "🐰", name: "Rabbit Face" },
  { character: "🐱", name: "Cat Face" },
  { character: "🐲", name: "Dragon Face" },
  { character: "🐳", name: "Spouting Whale" },
  { character: "🐴", name: "Horse Face" },
  { character: "🐵", name: "Monkey Face" },
  { character: "🐶", name: "Dog Face" },
  { character: "🐷", name: "Pig Face" },
  { character: "🐸", name: "Frog Face" },
  { character: "🐹", name: "Hamster Face" },
  { character: "🐺", name: "Wolf Face" },
  { character: "🐻", name: "Bear Face" },
  { character: "🐼", name: "Panda Face" },
  { character: "🐽", name: "Pig Nose" },
  { character: "🐾", name: "Paw Prints" },
  { character: "🐿", name: "Chipmunk" },
  { character: "👀", name: "Eyes" },
  { character: "👁", name: "Eye" },
  { character: "👂", name: "Ear" },
  { character: "👃", name: "Nose" },
  { character: "👄", name: "Mouth" },
  { character: "👅", name: "Tongue" },
  { character: "👆", name: "White Up Pointing Backhand Index" },
  { character: "👇", name: "White Down Pointing Backhand Index" },
  { character: "👈", name: "White Left Pointing Backhand Index" },
  { character: "👉", name: "White Right Pointing Backhand Index" },
  { character: "👊", name: "Fisted Hand Sign" },
  { character: "👋", name: "Waving Hand Sign" },
  { character: "👌", name: "Ok Hand Sign" },
  { character: "👍", name: "Thumbs Up Sign" },
  { character: "👎", name: "Thumbs Down Sign" },
  { character: "👏", name: "Clapping Hands Sign" },
  { character: "👐", name: "Open Hands Sign" },
  { character: "👑", name: "Crown" },
  { character: "👒", name: "Womans Hat" },
  { character: "👓", name: "Eyeglasses" },
  { character: "👔", name: "Necktie" },
  { character: "👕", name: "T-Shirt" },
  { character: "👖", name: "Jeans" },
  { character: "👗", name: "Dress" },
  { character: "👘", name: "Kimono" },
  { character: "👙", name: "Bikini" },
  { character: "👚", name: "Womans Clothes" },
  { character: "👛", name: "Purse" },
  { character: "👜", name: "Handbag" },
  { character: "👝", name: "Pouch" },
  { character: "👞", name: "Mans Shoe" },
  { character: "👟", name: "Athletic Shoe" },
  { character: "👠", name: "High-Heeled Shoe" },
  { character: "👡", name: "Womans Sandal" },
  { character: "👢", name: "Womans Boots" },
  { character: "👣", name: "Footprints" },
  { character: "👤", name: "Bust In Silhouette" },
  { character: "👥", name: "Busts In Silhouette" },
  { character: "👦", name: "Boy" },
  { character: "👧", name: "Girl" },
  { character: "👨", name: "Man" },
  { character: "👩", name: "Woman" },
  { character: "👪", name: "Family" },
  { character: "👫", name: "Man And Woman Holding Hands" },
  { character: "👬", name: "Two Men Holding Hands" },
  { character: "👭", name: "Two Women Holding Hands" },
  { character: "👮", name: "Police Officer" },
  { character: "👯", name: "Woman With Bunny Ears" },
  { character: "👰", name: "Bride With Veil" },
  { character: "👱", name: "Person With Blond Hair" },
  { character: "👲", name: "Man With Gua Pi Mao" },
  { character: "👳", name: "Man With Turban" },
  { character: "👴", name: "Older Man" },
  { character: "👵", name: "Older Woman" },
  { character: "👶", name: "Baby" },
  { character: "👷", name: "Construction Worker" },
  { character: "👸", name: "Princess" },
  { character: "👹", name: "Japanese Ogre" },
  { character: "👺", name: "Japanese Goblin" },
  { character: "👻", name: "Ghost" },
  { character: "👼", name: "Baby Angel" },
  { character: "👽", name: "Extraterrestrial Alien" },
  { character: "👾", name: "Alien Monster" },
  { character: "👿", name: "Imp" },
  { character: "💀", name: "Skull" },
  { character: "💁", name: "Information Desk Person" },
  { character: "💂", name: "Guardsman" },
  { character: "💃", name: "Dancer" },
  { character: "💄", name: "Lipstick" },
  { character: "💅", name: "Nail Polish" },
  { character: "💆", name: "Face Massage" },
  { character: "💇", name: "Haircut" },
  { character: "💈", name: "Barber Pole" },
  { character: "💉", name: "Syringe" },
  { character: "💊", name: "Pill" },
  { character: "💋", name: "Kiss Mark" },
  { character: "💌", name: "Love Letter" },
  { character: "💍", name: "Ring" },
  { character: "💎", name: "Gem Stone" },
  { character: "💏", name: "Kiss" },
  { character: "💐", name: "Bouquet" },
  { character: "💑", name: "Couple With Heart" },
  { character: "💒", name: "Wedding" },
  { character: "💓", name: "Beating Heart" },
  { character: "💔", name: "Broken Heart" },
  { character: "💕", name: "Two Hearts" },
  { character: "💖", name: "Sparkling Heart" },
  { character: "💗", name: "Growing Heart" },
  { character: "💘", name: "Heart With Arrow" },
  { character: "💙", name: "Blue Heart" },
  { character: "💚", name: "Green Heart" },
  { character: "💛", name: "Yellow Heart" },
  { character: "💜", name: "Purple Heart" },
  { character: "💝", name: "Heart With Ribbon" },
  { character: "💞", name: "Revolving Hearts" },
  { character: "💟", name: "Heart Decoration" },
  { character: "💠", name: "Diamond Shape With A Dot Inside" },
  { character: "💡", name: "Electric Light Bulb" },
  { character: "💢", name: "Anger Symbol" },
  { character: "💣", name: "Bomb" },
  { character: "💤", name: "Sleeping Symbol" },
  { character: "💥", name: "Collision Symbol" },
  { character: "💦", name: "Splashing Sweat Symbol" },
  { character: "💧", name: "Droplet" },
  { character: "💨", name: "Dash Symbol" },
  { character: "💩", name: "Pile Of Poo" },
  { character: "💪", name: "Flexed Biceps" },
  { character: "💫", name: "Dizzy Symbol" },
  { character: "💬", name: "Speech Balloon" },
  { character: "💭", name: "Thought Balloon" },
  { character: "💮", name: "White Flower" },
  { character: "💯", name: "Hundred Points Symbol" },
  { character: "💰", name: "Money Bag" },
  { character: "💱", name: "Currency Exchange" },
  { character: "💲", name: "Heavy Dollar Sign" },
  { character: "💳", name: "Credit Card" },
  { character: "💴", name: "Banknote With Yen Sign" },
  { character: "💵", name: "Banknote With Dollar Sign" },
  { character: "💶", name: "Banknote With Euro Sign" },
  { character: "💷", name: "Banknote With Pound Sign" },
  { character: "💸", name: "Money With Wings" },
  { character: "💹", name: "Chart With Upwards Trend And Yen Sign" },
  { character: "💺", name: "Seat" },
  { character: "💻", name: "Personal Computer" },
  { character: "💼", name: "Briefcase" },
  { character: "💽", name: "Minidisc" },
  { character: "💾", name: "Floppy Disk" },
  { character: "💿", name: "Optical Disc" },
  { character: "📀", name: "Dvd" },
  { character: "📁", name: "File Folder" },
  { character: "📂", name: "Open File Folder" },
  { character: "📃", name: "Page With Curl" },
  { character: "📄", name: "Page Facing Up" },
  { character: "📅", name: "Calendar" },
  { character: "📆", name: "Tear-Off Calendar" },
  { character: "📇", name: "Card Index" },
  { character: "📈", name: "Chart With Upwards Trend" },
  { character: "📉", name: "Chart With Downwards Trend" },
  { character: "📊", name: "Bar Chart" },
  { character: "📋", name: "Clipboard" },
  { character: "📌", name: "Pushpin" },
  { character: "📍", name: "Round Pushpin" },
  { character: "📎", name: "Paperclip" },
  { character: "📏", name: "Straight Ruler" },
  { character: "📐", name: "Triangular Ruler" },
  { character: "📑", name: "Bookmark Tabs" },
  { character: "📒", name: "Ledger" },
  { character: "📓", name: "Notebook" },
  { character: "📔", name: "Notebook With Decorative Cover" },
  { character: "📕", name: "Closed Book" },
  { character: "📖", name: "Open Book" },
  { character: "📗", name: "Green Book" },
  { character: "📘", name: "Blue Book" },
  { character: "📙", name: "Orange Book" },
  { character: "📚", name: "Books" },
  { character: "📛", name: "Name Badge" },
  { character: "📜", name: "Scroll" },
  { character: "📝", name: "Memo" },
  { character: "📞", name: "Telephone Receiver" },
  { character: "📟", name: "Pager" },
  { character: "📠", name: "Fax Machine" },
  { character: "📡", name: "Satellite Antenna" },
  { character: "📢", name: "Public Address Loudspeaker" },
  { character: "📣", name: "Cheering Megaphone" },
  { character: "📤", name: "Outbox Tray" },
  { character: "📥", name: "Inbox Tray" },
  { character: "📦", name: "Package" },
  { character: "📧", name: "E-Mail Symbol" },
  { character: "📨", name: "Incoming Envelope" },
  { character: "📩", name: "Envelope With Downwards Arrow Above" },
  { character: "📪", name: "Closed Mailbox With Lowered Flag" },
  { character: "📫", name: "Closed Mailbox With Raised Flag" },
  { character: "📬", name: "Open Mailbox With Raised Flag" },
  { character: "📭", name: "Open Mailbox With Lowered Flag" },
  { character: "📮", name: "Postbox" },
  { character: "📯", name: "Postal Horn" },
  { character: "📰", name: "Newspaper" },
  { character: "📱", name: "Mobile Phone" },
  { character: "📲", name: "Mobile Phone With Rightwards Arrow At Left" },
  { character: "📳", name: "Vibration Mode" },
  { character: "📴", name: "Mobile Phone Off" },
  { character: "📵", name: "No Mobile Phones" },
  { character: "📶", name: "Antenna With Bars" },
  { character: "📷", name: "Camera" },
  { character: "📸", name: "Camera With Flash" },
  { character: "📹", name: "Video Camera" },
  { character: "📺", name: "Television" },
  { character: "📻", name: "Radio" },
  { character: "📼", name: "Videocassette" },
  { character: "📽", name: "Film Projector" },
  { character: "📾", name: "Portable Stereo" },
  { character: "📿", name: "Prayer Beads" },
  { character: "🔀", name: "Twisted Rightwards Arrows" },
  { character: "🔁", name: "Clockwise Rightwards And Leftwards Open Circle Arrows" },
  { character: "🔂", name: "Clockwise Rightwards And Leftwards Open Circle Arrows With Circled One Overlay" },
  { character: "🔃", name: "Clockwise Downwards And Upwards Open Circle Arrows" },
  { character: "🔄", name: "Anticlockwise Downwards And Upwards Open Circle Arrows" },
  { character: "🔅", name: "Low Brightness Symbol" },
  { character: "🔆", name: "High Brightness Symbol" },
  { character: "🔇", name: "Speaker With Cancellation Stroke" },
  { character: "🔈", name: "Speaker" },
  { character: "🔉", name: "Speaker With One Sound Wave" },
  { character: "🔊", name: "Speaker With Three Sound Waves" },
  { character: "🔋", name: "Battery" },
  { character: "🔌", name: "Electric Plug" },
  { character: "🔍", name: "Left-Pointing Magnifying Glass" },
  { character: "🔎", name: "Right-Pointing Magnifying Glass" },
  { character: "🔏", name: "Lock With Ink Pen" },
  { character: "🔐", name: "Closed Lock With Key" },
  { character: "🔑", name: "Key" },
  { character: "🔒", name: "Lock" },
  { character: "🔓", name: "Open Lock" },
  { character: "🔔", name: "Bell" },
  { character: "🔕", name: "Bell With Cancellation Stroke" },
  { character: "🔖", name: "Bookmark" },
  { character: "🔗", name: "Link Symbol" },
  { character: "🔘", name: "Radio Button" },
  { character: "🔙", name: "Back With Leftwards Arrow Above" },
  { character: "🔚", name: "End With Leftwards Arrow Above" },
  { character: "🔛", name: "On With Exclamation Mark With Left Right Arrow Above" },
  { character: "🔜", name: "Soon With Rightwards Arrow Above" },
  { character: "🔝", name: "Top With Upwards Arrow Above" },
  { character: "🔞", name: "No One Under Eighteen Symbol" },
  { character: "🔟", name: "Keycap Ten" },
  { character: "🔠", name: "Input Symbol For Latin Capital Letters" },
  { character: "🔡", name: "Input Symbol For Latin Small Letters" },
  { character: "🔢", name: "Input Symbol For Numbers" },
  { character: "🔣", name: "Input Symbol For Symbols" },
  { character: "🔤", name: "Input Symbol For Latin Letters" },
  { character: "🔥", name: "Fire" },
  { character: "🔦", name: "Electric Torch" },
  { character: "🔧", name: "Wrench" },
  { character: "🔨", name: "Hammer" },
  { character: "🔩", name: "Nut And Bolt" },
  { character: "🔪", name: "Hocho" },
  { character: "🔫", name: "Pistol" },
  { character: "🔬", name: "Microscope" },
  { character: "🔭", name: "Telescope" },
  { character: "🔮", name: "Crystal Ball" },
  { character: "🔯", name: "Six Pointed Star With Middle Dot" },
  { character: "🔰", name: "Japanese Symbol For Beginner" },
  { character: "🔱", name: "Trident Emblem" },
  { character: "🔲", name: "Black Square Button" },
  { character: "🔳", name: "White Square Button" },
  { character: "🔴", name: "Large Red Circle" },
  { character: "🔵", name: "Large Blue Circle" },
  { character: "🔶", name: "Large Orange Diamond" },
  { character: "🔷", name: "Large Blue Diamond" },
  { character: "🔸", name: "Small Orange Diamond" },
  { character: "🔹", name: "Small Blue Diamond" },
  { character: "🔺", name: "Up-Pointing Red Triangle" },
  { character: "🔻", name: "Down-Pointing Red Triangle" },
  { character: "🔼", name: "Up-Pointing Small Red Triangle" },
  { character: "🔽", name: "Down-Pointing Small Red Triangle" },
  { character: "🔾", name: "Lower Right Shadowed White Circle" },
  { character: "🔿", name: "Upper Right Shadowed White Circle" },
  { character: "🕀", name: "Circled Cross Pommee" },
  { character: "🕁", name: "Cross Pommee With Half-Circle Below" },
  { character: "🕂", name: "Cross Pommee" },
  { character: "🕃", name: "Notched Left Semicircle With Three Dots" },
  { character: "🕄", name: "Notched Right Semicircle With Three Dots" },
  { character: "🕅", name: "Symbol For Marks Chapter" },
  { character: "🕆", name: "White Latin Cross" },
  { character: "🕇", name: "Heavy Latin Cross" },
  { character: "🕈", name: "Celtic Cross" },
  { character: "🕉", name: "Om Symbol" },
  { character: "🕊", name: "Dove Of Peace" },
  { character: "🕋", name: "Kaaba" },
  { character: "🕌", name: "Mosque" },
  { character: "🕍", name: "Synagogue" },
  { character: "🕎", name: "Menorah With Nine Branches" },
  { character: "🕏", name: "Bowl Of Hygieia" },
  { character: "🕐", name: "Clock Face One Oclock" },
  { character: "🕑", name: "Clock Face Two Oclock" },
  { character: "🕒", name: "Clock Face Three Oclock" },
  { character: "🕓", name: "Clock Face Four Oclock" },
  { character: "🕔", name: "Clock Face Five Oclock" },
  { character: "🕕", name: "Clock Face Six Oclock" },
  { character: "🕖", name: "Clock Face Seven Oclock" },
  { character: "🕗", name: "Clock Face Eight Oclock" },
  { character: "🕘", name: "Clock Face Nine Oclock" },
  { character: "🕙", name: "Clock Face Ten Oclock" },
  { character: "🕚", name: "Clock Face Eleven Oclock" },
  { character: "🕛", name: "Clock Face Twelve Oclock" },
  { character: "🕜", name: "Clock Face One-Thirty" },
  { character: "🕝", name: "Clock Face Two-Thirty" },
  { character: "🕞", name: "Clock Face Three-Thirty" },
  { character: "🕟", name: "Clock Face Four-Thirty" },
  { character: "🕠", name: "Clock Face Five-Thirty" },
  { character: "🕡", name: "Clock Face Six-Thirty" },
  { character: "🕢", name: "Clock Face Seven-Thirty" },
  { character: "🕣", name: "Clock Face Eight-Thirty" },
  { character: "🕤", name: "Clock Face Nine-Thirty" },
  { character: "🕥", name: "Clock Face Ten-Thirty" },
  { character: "🕦", name: "Clock Face Eleven-Thirty" },
  { character: "🕧", name: "Clock Face Twelve-Thirty" },
  { character: "🕨", name: "Right Speaker" },
  { character: "🕩", name: "Right Speaker With One Sound Wave" },
  { character: "🕪", name: "Right Speaker With Three Sound Waves" },
  { character: "🕫", name: "Bullhorn" },
  { character: "🕬", name: "Bullhorn With Sound Waves" },
  { character: "🕭", name: "Ringing Bell" },
  { character: "🕮", name: "Book" },
  { character: "🕯", name: "Candle" },
  { character: "🕰", name: "Mantelpiece Clock" },
  { character: "🕱", name: "Black Skull And Crossbones" },
  { character: "🕲", name: "No Piracy" },
  { character: "🕳", name: "Hole" },
  { character: "🕴", name: "Man In Business Suit Levitating" },
  { character: "🕵", name: "Sleuth Or Spy" },
  { character: "🕶", name: "Dark Sunglasses" },
  { character: "🕷", name: "Spider" },
  { character: "🕸", name: "Spider Web" },
  { character: "🕹", name: "Joystick" },
  { character: "🕺", name: "Man Dancing" },
  { character: "🕻", name: "Left Hand Telephone Receiver" },
  { character: "🕼", name: "Telephone Receiver With Page" },
  { character: "🕽", name: "Right Hand Telephone Receiver" },
  { character: "🕾", name: "White Touchtone Telephone" },
  { character: "🕿", name: "Black Touchtone Telephone" },
  { character: "🖀", name: "Telephone On Top Of Modem" },
  { character: "🖁", name: "Clamshell Mobile Phone" },
  { character: "🖂", name: "Back Of Envelope" },
  { character: "🖃", name: "Stamped Envelope" },
  { character: "🖄", name: "Envelope With Lightning" },
  { character: "🖅", name: "Flying Envelope" },
  { character: "🖆", name: "Pen Over Stamped Envelope" },
  { character: "🖇", name: "Linked Paperclips" },
  { character: "🖈", name: "Black Pushpin" },
  { character: "🖉", name: "Lower Left Pencil" },
  { character: "🖊", name: "Lower Left Ballpoint Pen" },
  { character: "🖋", name: "Lower Left Fountain Pen" },
  { character: "🖌", name: "Lower Left Paintbrush" },
  { character: "🖍", name: "Lower Left Crayon" },
  { character: "🖎", name: "Left Writing Hand" },
  { character: "🖏", name: "Turned Ok Hand Sign" },
  { character: "🖐", name: "Raised Hand With Fingers Splayed" },
  { character: "🖑", name: "Reversed Raised Hand With Fingers Splayed" },
  { character: "🖒", name: "Reversed Thumbs Up Sign" },
  { character: "🖓", name: "Reversed Thumbs Down Sign" },
  { character: "🖔", name: "Reversed Victory Hand" },
  { character: "🖕", name: "Reversed Hand With Middle Finger Extended" },
  { character: "🖖", name: "Raised Hand With Part Between Middle And Ring Fingers" },
  { character: "🖗", name: "White Down Pointing Left Hand Index" },
  { character: "🖘", name: "Sideways White Left Pointing Index" },
  { character: "🖙", name: "Sideways White Right Pointing Index" },
  { character: "🖚", name: "Sideways Black Left Pointing Index" },
  { character: "🖛", name: "Sideways Black Right Pointing Index" },
  { character: "🖜", name: "Black Left Pointing Backhand Index" },
  { character: "🖝", name: "Black Right Pointing Backhand Index" },
  { character: "🖞", name: "Sideways White Up Pointing Index" },
  { character: "🖟", name: "Sideways White Down Pointing Index" },
  { character: "🖠", name: "Sideways Black Up Pointing Index" },
  { character: "🖡", name: "Sideways Black Down Pointing Index" },
  { character: "🖢", name: "Black Up Pointing Backhand Index" },
  { character: "🖣", name: "Black Down Pointing Backhand Index" },
  { character: "🖤", name: "Black Heart" },
  { character: "🖥", name: "Desktop Computer" },
  { character: "🖦", name: "Keyboard And Mouse" },
  { character: "🖧", name: "Three Networked Computers" },
  { character: "🖨", name: "Printer" },
  { character: "🖩", name: "Pocket Calculator" },
  { character: "🖪", name: "Black Hard Shell Floppy Disk" },
  { character: "🖫", name: "White Hard Shell Floppy Disk" },
  { character: "🖬", name: "Soft Shell Floppy Disk" },
  { character: "🖭", name: "Tape Cartridge" },
  { character: "🖮", name: "Wired Keyboard" },
  { character: "🖯", name: "One Button Mouse" },
  { character: "🖰", name: "Two Button Mouse" },
  { character: "🖱", name: "Three Button Mouse" },
  { character: "🖲", name: "Trackball" },
  { character: "🖳", name: "Old Personal Computer" },
  { character: "🖴", name: "Hard Disk" },
  { character: "🖵", name: "Screen" },
  { character: "🖶", name: "Printer Icon" },
  { character: "🖷", name: "Fax Icon" },
  { character: "🖸", name: "Optical Disc Icon" },
  { character: "🖹", name: "Document With Text" },
  { character: "🖺", name: "Document With Text And Picture" },
  { character: "🖻", name: "Document With Picture" },
  { character: "🖼", name: "Frame With Picture" },
  { character: "🖽", name: "Frame With Tiles" },
  { character: "🖾", name: "Frame With An X" },
  { character: "🖿", name: "Black Folder" },
  { character: "🗀", name: "Folder" },
  { character: "🗁", name: "Open Folder" },
  { character: "🗂", name: "Card Index Dividers" },
  { character: "🗃", name: "Card File Box" },
  { character: "🗄", name: "File Cabinet" },
  { character: "🗅", name: "Empty Note" },
  { character: "🗆", name: "Empty Note Page" },
  { character: "🗇", name: "Empty Note Pad" },
  { character: "🗈", name: "Note" },
  { character: "🗉", name: "Note Page" },
  { character: "🗊", name: "Note Pad" },
  { character: "🗋", name: "Empty Document" },
  { character: "🗌", name: "Empty Page" },
  { character: "🗍", name: "Empty Pages" },
  { character: "🗎", name: "Document" },
  { character: "🗏", name: "Page" },
  { character: "🗐", name: "Pages" },
  { character: "🗑", name: "Wastebasket" },
  { character: "🗒", name: "Spiral Note Pad" },
  { character: "🗓", name: "Spiral Calendar Pad" },
  { character: "🗔", name: "Desktop Window" },
  { character: "🗕", name: "Minimize" },
  { character: "🗖", name: "Maximize" },
  { character: "🗗", name: "Overlap" },
  { character: "🗘", name: "Clockwise Right And Left Semicircle Arrows" },
  { character: "🗙", name: "Cancellation X" },
  { character: "🗚", name: "Increase Font Size Symbol" },
  { character: "🗛", name: "Decrease Font Size Symbol" },
  { character: "🗜", name: "Compression" },
  { character: "🗝", name: "Old Key" },
  { character: "🗞", name: "Rolled-Up Newspaper" },
  { character: "🗟", name: "Page With Circled Text" },
  { character: "🗠", name: "Stock Chart" },
  { character: "🗡", name: "Dagger Knife" },
  { character: "🗢", name: "Lips" },
  { character: "🗣", name: "Speaking Head In Silhouette" },
  { character: "🗤", name: "Three Rays Above" },
  { character: "🗥", name: "Three Rays Below" },
  { character: "🗦", name: "Three Rays Left" },
  { character: "🗧", name: "Three Rays Right" },
  { character: "🗨", name: "Left Speech Bubble" },
  { character: "🗩", name: "Right Speech Bubble" },
  { character: "🗪", name: "Two Speech Bubbles" },
  { character: "🗫", name: "Three Speech Bubbles" },
  { character: "🗬", name: "Left Thought Bubble" },
  { character: "🗭", name: "Right Thought Bubble" },
  { character: "🗮", name: "Left Anger Bubble" },
  { character: "🗯", name: "Right Anger Bubble" },
  { character: "🗰", name: "Mood Bubble" },
  { character: "🗱", name: "Lightning Mood Bubble" },
  { character: "🗲", name: "Lightning Mood" },
  { character: "🗳", name: "Ballot Box With Ballot" },
  { character: "🗴", name: "Ballot Script X" },
  { character: "🗵", name: "Ballot Box With Script X" },
  { character: "🗶", name: "Ballot Bold Script X" },
  { character: "🗷", name: "Ballot Box With Bold Script X" },
  { character: "🗸", name: "Light Check Mark" },
  { character: "🗹", name: "Ballot Box With Bold Check" },
  { character: "🗺", name: "World Map" },
  { character: "🗻", name: "Mount Fuji" },
  { character: "🗼", name: "Tokyo Tower" },
  { character: "🗽", name: "Statue Of Liberty" },
  { character: "🗾", name: "Silhouette Of Japan" },
  { character: "🗿", name: "Moyai" },
  { character: "😀", name: "Grinning Face" },
  { character: "😁", name: "Grinning Face With Smiling Eyes" },
  { character: "😂", name: "Face With Tears Of Joy" },
  { character: "😃", name: "Smiling Face With Open Mouth" },
  { character: "😄", name: "Smiling Face With Open Mouth And Smiling Eyes" },
  { character: "😅", name: "Smiling Face With Open Mouth And Cold Sweat" },
  { character: "😆", name: "Smiling Face With Open Mouth And Tightly-Closed Eyes" },
  { character: "😇", name: "Smiling Face With Halo" },
  { character: "😈", name: "Smiling Face With Horns" },
  { character: "😉", name: "Winking Face" },
  { character: "😊", name: "Smiling Face With Smiling Eyes" },
  { character: "😋", name: "Face Savouring Delicious Food" },
  { character: "😌", name: "Relieved Face" },
  { character: "😍", name: "Smiling Face With Heart-Shaped Eyes" },
  { character: "😎", name: "Smiling Face With Sunglasses" },
  { character: "😏", name: "Smirking Face" },
  { character: "😐", name: "Neutral Face" },
  { character: "😑", name: "Expressionless Face" },
  { character: "😒", name: "Unamused Face" },
  { character: "😓", name: "Face With Cold Sweat" },
  { character: "😔", name: "Pensive Face" },
  { character: "😕", name: "Confused Face" },
  { character: "😖", name: "Confounded Face" },
  { character: "😗", name: "Kissing Face" },
  { character: "😘", name: "Face Throwing A Kiss" },
  { character: "😙", name: "Kissing Face With Smiling Eyes" },
  { character: "😚", name: "Kissing Face With Closed Eyes" },
  { character: "😛", name: "Face With Stuck-Out Tongue" },
  { character: "😜", name: "Face With Stuck-Out Tongue And Winking Eye" },
  { character: "😝", name: "Face With Stuck-Out Tongue And Tightly-Closed Eyes" },
  { character: "😞", name: "Disappointed Face" },
  { character: "😟", name: "Worried Face" },
  { character: "😠", name: "Angry Face" },
  { character: "😡", name: "Pouting Face" },
  { character: "😢", name: "Crying Face" },
  { character: "😣", name: "Persevering Face" },
  { character: "😤", name: "Face With Look Of Triumph" },
  { character: "😥", name: "Disappointed But Relieved Face" },
  { character: "😦", name: "Frowning Face With Open Mouth" },
  { character: "😧", name: "Anguished Face" },
  { character: "😨", name: "Fearful Face" },
  { character: "😩", name: "Weary Face" },
  { character: "😪", name: "Sleepy Face" },
  { character: "😫", name: "Tired Face" },
  { character: "😬", name: "Grimacing Face" },
  { character: "😭", name: "Loudly Crying Face" },
  { character: "😮", name: "Face With Open Mouth" },
  { character: "😯", name: "Hushed Face" },
  { character: "😰", name: "Face With Open Mouth And Cold Sweat" },
  { character: "😱", name: "Face Screaming In Fear" },
  { character: "😲", name: "Astonished Face" },
  { character: "😳", name: "Flushed Face" },
  { character: "😴", name: "Sleeping Face" },
  { character: "😵", name: "Dizzy Face" },
  { character: "😶", name: "Face Without Mouth" },
  { character: "😷", name: "Face With Medical Mask" },
  { character: "😸", name: "Grinning Cat Face With Smiling Eyes" },
  { character: "😹", name: "Cat Face With Tears Of Joy" },
  { character: "😺", name: "Smiling Cat Face With Open Mouth" },
  { character: "😻", name: "Smiling Cat Face With Heart-Shaped Eyes" },
  { character: "😼", name: "Cat Face With Wry Smile" },
  { character: "😽", name: "Kissing Cat Face With Closed Eyes" },
  { character: "😾", name: "Pouting Cat Face" },
  { character: "😿", name: "Crying Cat Face" },
  { character: "🙀", name: "Weary Cat Face" },
  { character: "🙁", name: "Slightly Frowning Face" },
  { character: "🙂", name: "Slightly Smiling Face" },
  { character: "🙃", name: "Upside-Down Face" },
  { character: "🙄", name: "Face With Rolling Eyes" },
  { character: "🙅", name: "Face With No Good Gesture" },
  { character: "🙆", name: "Face With Ok Gesture" },
  { character: "🙇", name: "Person Bowing Deeply" },
  { character: "🙈", name: "See-No-Evil Monkey" },
  { character: "🙉", name: "Hear-No-Evil Monkey" },
  { character: "🙊", name: "Speak-No-Evil Monkey" },
  { character: "🙋", name: "Happy Person Raising One Hand" },
  { character: "🙌", name: "Person Raising Both Hands In Celebration" },
  { character: "🙍", name: "Person Frowning" },
  { character: "🙎", name: "Person With Pouting Face" },
  { character: "🙏", name: "Person With Folded Hands" },
  { character: "🚀", name: "Rocket" },
  { character: "🚁", name: "Helicopter" },
  { character: "🚂", name: "Steam Locomotive" },
  { character: "🚃", name: "Railway Car" },
  { character: "🚄", name: "High-Speed Train" },
  { character: "🚅", name: "High-Speed Train With Bullet Nose" },
  { character: "🚆", name: "Train" },
  { character: "🚇", name: "Metro" },
  { character: "🚈", name: "Light Rail" },
  { character: "🚉", name: "Station" },
  { character: "🚊", name: "Tram" },
  { character: "🚋", name: "Tram Car" },
  { character: "🚌", name: "Bus" },
  { character: "🚍", name: "Oncoming Bus" },
  { character: "🚎", name: "Trolleybus" },
  { character: "🚏", name: "Bus Stop" },
  { character: "🚐", name: "Minibus" },
  { character: "🚑", name: "Ambulance" },
  { character: "🚒", name: "Fire Engine" },
  { character: "🚓", name: "Police Car" },
  { character: "🚔", name: "Oncoming Police Car" },
  { character: "🚕", name: "Taxi" },
  { character: "🚖", name: "Oncoming Taxi" },
  { character: "🚗", name: "Automobile" },
  { character: "🚘", name: "Oncoming Automobile" },
  { character: "🚙", name: "Recreational Vehicle" },
  { character: "🚚", name: "Delivery Truck" },
  { character: "🚛", name: "Articulated Lorry" },
  { character: "🚜", name: "Tractor" },
  { character: "🚝", name: "Monorail" },
  { character: "🚞", name: "Mountain Railway" },
  { character: "🚟", name: "Suspension Railway" },
  { character: "🚠", name: "Mountain Cableway" },
  { character: "🚡", name: "Aerial Tramway" },
  { character: "🚢", name: "Ship" },
  { character: "🚣", name: "Rowboat" },
  { character: "🚤", name: "Speedboat" },
  { character: "🚥", name: "Horizontal Traffic Light" },
  { character: "🚦", name: "Vertical Traffic Light" },
  { character: "🚧", name: "Construction Sign" },
  { character: "🚨", name: "Police Cars Revolving Light" },
  { character: "🚩", name: "Triangular Flag On Post" },
  { character: "🚪", name: "Door" },
  { character: "🚫", name: "No Entry Sign" },
  { character: "🚬", name: "Smoking Symbol" },
  { character: "🚭", name: "No Smoking Symbol" },
  { character: "🚮", name: "Put Litter In Its Place Symbol" },
  { character: "🚯", name: "Do Not Litter Symbol" },
  { character: "🚰", name: "Potable Water Symbol" },
  { character: "🚱", name: "Non-Potable Water Symbol" },
  { character: "🚲", name: "Bicycle" },
  { character: "🚳", name: "No Bicycles" },
  { character: "🚴", name: "Bicyclist" },
  { character: "🚵", name: "Mountain Bicyclist" },
  { character: "🚶", name: "Pedestrian" },
  { character: "🚷", name: "No Pedestrians" },
  { character: "🚸", name: "Children Crossing" },
  { character: "🚹", name: "Mens Symbol" },
  { character: "🚺", name: "Womens Symbol" },
  { character: "🚻", name: "Restroom" },
  { character: "🚼", name: "Baby Symbol" },
  { character: "🚽", name: "Toilet" },
  { character: "🚾", name: "Water Closet" },
  { character: "🚿", name: "Shower" },
  { character: "🛀", name: "Bath" },
  { character: "🛁", name: "Bathtub" },
  { character: "🛂", name: "Passport Control" },
  { character: "🛃", name: "Customs" },
  { character: "🛄", name: "Baggage Claim" },
  { character: "🛅", name: "Left Luggage" },
  { character: "🛆", name: "Triangle With Rounded Corners" },
  { character: "🛇", name: "Prohibited Sign" },
  { character: "🛈", name: "Circled Information Source" },
  { character: "🛉", name: "Boys Symbol" },
  { character: "🛊", name: "Girls Symbol" },
  { character: "🛋", name: "Couch And Lamp" },
  { character: "🛌", name: "Sleeping Accommodation" },
  { character: "🛍", name: "Shopping Bags" },
  { character: "🛎", name: "Bellhop Bell" },
  { character: "🛏", name: "Bed" },
  { character: "🛐", name: "Place Of Worship" },
  { character: "🛑", name: "Octagonal Sign" },
  { character: "🛒", name: "Shopping Trolley" },
  { character: "🛓", name: "Stupa" },
  { character: "🛔", name: "Pagoda" },
  { character: "🛕", name: "Hindu Temple" },
  { character: "🛖", name: "Hut" },
  { character: "🛗", name: "Elevator" },
  { character: "🛜", name: "Wireless" },
  { character: "🛝", name: "Playground Slide" },
  { character: "🛞", name: "Wheel" },
  { character: "🛟", name: "Ring Buoy" },
  { character: "🛠", name: "Hammer And Wrench" },
  { character: "🛡", name: "Shield" },
  { character: "🛢", name: "Oil Drum" },
  { character: "🛣", name: "Motorway" },
  { character: "🛤", name: "Railway Track" },
  { character: "🛥", name: "Motor Boat" },
  { character: "🛦", name: "Up-Pointing Military Airplane" },
  { character: "🛧", name: "Up-Pointing Airplane" },
  { character: "🛨", name: "Up-Pointing Small Airplane" },
  { character: "🛩", name: "Small Airplane" },
  { character: "🛪", name: "Northeast-Pointing Airplane" },
  { character: "🛫", name: "Airplane Departure" },
  { character: "🛬", name: "Airplane Arriving" },
  { character: "🛰", name: "Satellite" },
  { character: "🛱", name: "Oncoming Fire Engine" },
  { character: "🛲", name: "Diesel Locomotive" },
  { character: "🛳", name: "Passenger Ship" },
  { character: "🛴", name: "Scooter" },
  { character: "🛵", name: "Motor Scooter" },
  { character: "🛶", name: "Canoe" },
  { character: "🛷", name: "Sled" },
  { character: "🛸", name: "Flying Saucer" },
  { character: "🛹", name: "Skateboard" },
  { character: "🛺", name: "Auto Rickshaw" },
  { character: "🛻", name: "Pickup Truck" },
  { character: "🛼", name: "Roller Skate" },
  { character: "🤀", name: "Circled Cross Formee With Four Dots" },
  { character: "🤁", name: "Circled Cross Formee With Two Dots" },
  { character: "🤂", name: "Circled Cross Formee" },
  { character: "🤃", name: "Left Half Circle With Four Dots" },
  { character: "🤄", name: "Left Half Circle With Three Dots" },
  { character: "🤅", name: "Left Half Circle With Two Dots" },
  { character: "🤆", name: "Left Half Circle With Dot" },
  { character: "🤇", name: "Left Half Circle" },
  { character: "🤈", name: "Downward Facing Hook" },
  { character: "🤉", name: "Downward Facing Notched Hook" },
  { character: "🤊", name: "Downward Facing Hook With Dot" },
  { character: "🤋", name: "Downward Facing Notched Hook With Dot" },
  { character: "🤌", name: "Pinched Fingers" },
  { character: "🤍", name: "White Heart" },
  { character: "🤎", name: "Brown Heart" },
  { character: "🤏", name: "Pinching Hand" },
  { character: "🤐", name: "Zipper-Mouth Face" },
  { character: "🤑", name: "Money-Mouth Face" },
  { character: "🤒", name: "Face With Thermometer" },
  { character: "🤓", name: "Nerd Face" },
  { character: "🤔", name: "Thinking Face" },
  { character: "🤕", name: "Face With Head-Bandage" },
  { character: "🤖", name: "Robot Face" },
  { character: "🤗", name: "Hugging Face" },
  { character: "🤘", name: "Sign Of The Horns" },
  { character: "🤙", name: "Call Me Hand" },
  { character: "🤚", name: "Raised Back Of Hand" },
  { character: "🤛", name: "Left-Facing Fist" },
  { character: "🤜", name: "Right-Facing Fist" },
  { character: "🤝", name: "Handshake" },
  { character: "🤞", name: "Hand With Index And Middle Fingers Crossed" },
  { character: "🤟", name: "I Love You Hand Sign" },
  { character: "🤠", name: "Face With Cowboy Hat" },
  { character: "🤡", name: "Clown Face" },
  { character: "🤢", name: "Nauseated Face" },
  { character: "🤣", name: "Rolling On The Floor Laughing" },
  { character: "🤤", name: "Drooling Face" },
  { character: "🤥", name: "Lying Face" },
  { character: "🤦", name: "Face Palm" },
  { character: "🤧", name: "Sneezing Face" },
  { character: "🤨", name: "Face With One Eyebrow Raised" },
  { character: "🤩", name: "Grinning Face With Star Eyes" },
  { character: "🤪", name: "Grinning Face With One Large And One Small Eye" },
  { character: "🤫", name: "Face With Finger Covering Closed Lips" },
  { character: "🤬", name: "Serious Face With Symbols Covering Mouth" },
  { character: "🤭", name: "Smiling Face With Smiling Eyes And Hand Covering Mouth" },
  { character: "🤮", name: "Face With Open Mouth Vomiting" },
  { character: "🤯", name: "Shocked Face With Exploding Head" },
  { character: "🤰", name: "Pregnant Woman" },
  { character: "🤱", name: "Breast-Feeding" },
  { character: "🤲", name: "Palms Up Together" },
  { character: "🤳", name: "Selfie" },
  { character: "🤴", name: "Prince" },
  { character: "🤵", name: "Man In Tuxedo" },
  { character: "🤶", name: "Mother Christmas" },
  { character: "🤷", name: "Shrug" },
  { character: "🤸", name: "Person Doing Cartwheel" },
  { character: "🤹", name: "Juggling" },
  { character: "🤺", name: "Fencer" },
  { character: "🤻", name: "Modern Pentathlon" },
  { character: "🤼", name: "Wrestlers" },
  { character: "🤽", name: "Water Polo" },
  { character: "🤾", name: "Handball" },
  { character: "🤿", name: "Diving Mask" },
  { character: "🥀", name: "Wilted Flower" },
  { character: "🥁", name: "Drum With Drumsticks" },
  { character: "🥂", name: "Clinking Glasses" },
  { character: "🥃", name: "Tumbler Glass" },
  { character: "🥄", name: "Spoon" },
  { character: "🥅", name: "Goal Net" },
  { character: "🥆", name: "Rifle" },
  { character: "🥇", name: "First Place Medal" },
  { character: "🥈", name: "Second Place Medal" },
  { character: "🥉", name: "Third Place Medal" },
  { character: "🥊", name: "Boxing Glove" },
  { character: "🥋", name: "Martial Arts Uniform" },
  { character: "🥌", name: "Curling Stone" },
  { character: "🥍", name: "Lacrosse Stick And Ball" },
  { character: "🥎", name: "Softball" },
  { character: "🥏", name: "Flying Disc" },
  { character: "🥐", name: "Croissant" },
  { character: "🥑", name: "Avocado" },
  { character: "🥒", name: "Cucumber" },
  { character: "🥓", name: "Bacon" },
  { character: "🥔", name: "Potato" },
  { character: "🥕", name: "Carrot" },
  { character: "🥖", name: "Baguette Bread" },
  { character: "🥗", name: "Green Salad" },
  { character: "🥘", name: "Shallow Pan Of Food" },
  { character: "🥙", name: "Stuffed Flatbread" },
  { character: "🥚", name: "Egg" },
  { character: "🥛", name: "Glass Of Milk" },
  { character: "🥜", name: "Peanuts" },
  { character: "🥝", name: "Kiwifruit" },
  { character: "🥞", name: "Pancakes" },
  { character: "🥟", name: "Dumpling" },
  { character: "🥠", name: "Fortune Cookie" },
  { character: "🥡", name: "Takeout Box" },
  { character: "🥢", name: "Chopsticks" },
  { character: "🥣", name: "Bowl With Spoon" },
  { character: "🥤", name: "Cup With Straw" },
  { character: "🥥", name: "Coconut" },
  { character: "🥦", name: "Broccoli" },
  { character: "🥧", name: "Pie" },
  { character: "🥨", name: "Pretzel" },
  { character: "🥩", name: "Cut Of Meat" },
  { character: "🥪", name: "Sandwich" },
  { character: "🥫", name: "Canned Food" },
  { character: "🥬", name: "Leafy Green" },
  { character: "🥭", name: "Mango" },
  { character: "🥮", name: "Moon Cake" },
  { character: "🥯", name: "Bagel" },
  { character: "🥰", name: "Smiling Face With Smiling Eyes And Three Hearts" },
  { character: "🥱", name: "Yawning Face" },
  { character: "🥲", name: "Smiling Face With Tear" },
  { character: "🥳", name: "Face With Party Horn And Party Hat" },
  { character: "🥴", name: "Face With Uneven Eyes And Wavy Mouth" },
  { character: "🥵", name: "Overheated Face" },
  { character: "🥶", name: "Freezing Face" },
  { character: "🥷", name: "Ninja" },
  { character: "🥸", name: "Disguised Face" },
  { character: "🥹", name: "Face Holding Back Tears" },
  { character: "🥺", name: "Face With Pleading Eyes" },
  { character: "🥻", name: "Sari" },
  { character: "🥼", name: "Lab Coat" },
  { character: "🥽", name: "Goggles" },
  { character: "🥾", name: "Hiking Boot" },
  { character: "🥿", name: "Flat Shoe" },
  { character: "🦀", name: "Crab" },
  { character: "🦁", name: "Lion Face" },
  { character: "🦂", name: "Scorpion" },
  { character: "🦃", name: "Turkey" },
  { character: "🦄", name: "Unicorn Face" },
  { character: "🦅", name: "Eagle" },
  { character: "🦆", name: "Duck" },
  { character: "🦇", name: "Bat" },
  { character: "🦈", name: "Shark" },
  { character: "🦉", name: "Owl" },
  { character: "🦊", name: "Fox Face" },
  { character: "🦋", name: "Butterfly" },
  { character: "🦌", name: "Deer" },
  { character: "🦍", name: "Gorilla" },
  { character: "🦎", name: "Lizard" },
  { character: "🦏", name: "Rhinoceros" },
  { character: "🦐", name: "Shrimp" },
  { character: "🦑", name: "Squid" },
  { character: "🦒", name: "Giraffe Face" },
  { character: "🦓", name: "Zebra Face" },
  { character: "🦔", name: "Hedgehog" },
  { character: "🦕", name: "Sauropod" },
  { character: "🦖", name: "T-Rex" },
  { character: "🦗", name: "Cricket" },
  { character: "🦘", name: "Kangaroo" },
  { character: "🦙", name: "Llama" },
  { character: "🦚", name: "Peacock" },
  { character: "🦛", name: "Hippopotamus" },
  { character: "🦜", name: "Parrot" },
  { character: "🦝", name: "Raccoon" },
  { character: "🦞", name: "Lobster" },
  { character: "🦟", name: "Mosquito" },
  { character: "🦠", name: "Microbe" },
  { character: "🦡", name: "Badger" },
  { character: "🦢", name: "Swan" },
  { character: "🦣", name: "Mammoth" },
  { character: "🦤", name: "Dodo" },
  { character: "🦥", name: "Sloth" },
  { character: "🦦", name: "Otter" },
  { character: "🦧", name: "Orangutan" },
  { character: "🦨", name: "Skunk" },
  { character: "🦩", name: "Flamingo" },
  { character: "🦪", name: "Oyster" },
  { character: "🦫", name: "Beaver" },
  { character: "🦬", name: "Bison" },
  { character: "🦭", name: "Seal" },
  { character: "🦮", name: "Guide Dog" },
  { character: "🦯", name: "Probing Cane" },
  { character: "🦰", name: "Emoji Component Red Hair" },
  { character: "🦱", name: "Emoji Component Curly Hair" },
  { character: "🦲", name: "Emoji Component Bald" },
  { character: "🦳", name: "Emoji Component White Hair" },
  { character: "🦴", name: "Bone" },
  { character: "🦵", name: "Leg" },
  { character: "🦶", name: "Foot" },
  { character: "🦷", name: "Tooth" },
  { character: "🦸", name: "Superhero" },
  { character: "🦹", name: "Supervillain" },
  { character: "🦺", name: "Safety Vest" },
  { character: "🦻", name: "Ear With Hearing Aid" },
  { character: "🦼", name: "Motorized Wheelchair" },
  { character: "🦽", name: "Manual Wheelchair" },
  { character: "🦾", name: "Mechanical Arm" },
  { character: "🦿", name: "Mechanical Leg" },
  { character: "🧀", name: "Cheese Wedge" },
  { character: "🧁", name: "Cupcake" },
  { character: "🧂", name: "Salt Shaker" },
  { character: "🧃", name: "Beverage Box" },
  { character: "🧄", name: "Garlic" },
  { character: "🧅", name: "Onion" },
  { character: "🧆", name: "Falafel" },
  { character: "🧇", name: "Waffle" },
  { character: "🧈", name: "Butter" },
  { character: "🧉", name: "Mate Drink" },
  { character: "🧊", name: "Ice Cube" },
  { character: "🧋", name: "Bubble Tea" },
  { character: "🧌", name: "Troll" },
  { character: "🧍", name: "Standing Person" },
  { character: "🧎", name: "Kneeling Person" },
  { character: "🧏", name: "Deaf Person" },
  { character: "🧐", name: "Face With Monocle" },
  { character: "🧑", name: "Adult" },
  { character: "🧒", name: "Child" },
  { character: "🧓", name: "Older Adult" },
  { character: "🧔", name: "Bearded Person" },
  { character: "🧕", name: "Person With Headscarf" },
  { character: "🧖", name: "Person In Steamy Room" },
  { character: "🧗", name: "Person Climbing" },
  { character: "🧘", name: "Person In Lotus Position" },
  { character: "🧙", name: "Mage" },
  { character: "🧚", name: "Fairy" },
  { character: "🧛", name: "Vampire" },
  { character: "🧜", name: "Merperson" },
  { character: "🧝", name: "Elf" },
  { character: "🧞", name: "Genie" },
  { character: "🧟", name: "Zombie" },
  { character: "🧠", name: "Brain" },
  { character: "🧡", name: "Orange Heart" },
  { character: "🧢", name: "Billed Cap" },
  { character: "🧣", name: "Scarf" },
  { character: "🧤", name: "Gloves" },
  { character: "🧥", name: "Coat" },
  { character: "🧦", name: "Socks" },
  { character: "🧧", name: "Red Gift Envelope" },
  { character: "🧨", name: "Firecracker" },
  { character: "🧩", name: "Jigsaw Puzzle Piece" },
  { character: "🧪", name: "Test Tube" },
  { character: "🧫", name: "Petri Dish" },
  { character: "🧬", name: "Dna Double Helix" },
  { character: "🧭", name: "Compass" },
  { character: "🧮", name: "Abacus" },
  { character: "🧯", name: "Fire Extinguisher" },
  { character: "🧰", name: "Toolbox" },
  { character: "🧱", name: "Brick" },
  { character: "🧲", name: "Magnet" },
  { character: "🧳", name: "Luggage" },
  { character: "🧴", name: "Lotion Bottle" },
  { character: "🧵", name: "Spool Of Thread" },
  { character: "🧶", name: "Ball Of Yarn" },
  { character: "🧷", name: "Safety Pin" },
  { character: "🧸", name: "Teddy Bear" },
  { character: "🧹", name: "Broom" },
  { character: "🧺", name: "Basket" },
  { character: "🧻", name: "Roll Of Paper" },
  { character: "🧼", name: "Bar Of Soap" },
  { character: "🧽", name: "Sponge" },
  { character: "🧾", name: "Receipt" },
  { character: "🧿", name: "Nazar Amulet" },
  { character: "🨀", name: "Neutral Chess King" },
  { character: "🨁", name: "Neutral Chess Queen" },
  { character: "🨂", name: "Neutral Chess Rook" },
  { character: "🨃", name: "Neutral Chess Bishop" },
  { character: "🨄", name: "Neutral Chess Knight" },
  { character: "🨅", name: "Neutral Chess Pawn" },
  { character: "🨆", name: "White Chess Knight Rotated Forty-Five Degrees" },
  { character: "🨇", name: "Black Chess Knight Rotated Forty-Five Degrees" },
  { character: "🨈", name: "Neutral Chess Knight Rotated Forty-Five Degrees" },
  { character: "🨉", name: "White Chess King Rotated Ninety Degrees" },
  { character: "🨊", name: "White Chess Queen Rotated Ninety Degrees" },
  { character: "🨋", name: "White Chess Rook Rotated Ninety Degrees" },
  { character: "🨌", name: "White Chess Bishop Rotated Ninety Degrees" },
  { character: "🨍", name: "White Chess Knight Rotated Ninety Degrees" },
  { character: "🨎", name: "White Chess Pawn Rotated Ninety Degrees" },
  { character: "🨏", name: "Black Chess King Rotated Ninety Degrees" },
  { character: "🨐", name: "Black Chess Queen Rotated Ninety Degrees" },
  { character: "🨑", name: "Black Chess Rook Rotated Ninety Degrees" },
  { character: "🨒", name: "Black Chess Bishop Rotated Ninety Degrees" },
  { character: "🨓", name: "Black Chess Knight Rotated Ninety Degrees" },
  { character: "🨔", name: "Black Chess Pawn Rotated Ninety Degrees" },
  { character: "🨕", name: "Neutral Chess King Rotated Ninety Degrees" },
  { character: "🨖", name: "Neutral Chess Queen Rotated Ninety Degrees" },
  { character: "🨗", name: "Neutral Chess Rook Rotated Ninety Degrees" },
  { character: "🨘", name: "Neutral Chess Bishop Rotated Ninety Degrees" },
  { character: "🨙", name: "Neutral Chess Knight Rotated Ninety Degrees" },
  { character: "🨚", name: "Neutral Chess Pawn Rotated Ninety Degrees" },
  { character: "🨛", name: "White Chess Knight Rotated One Hundred Thirty-Five Degrees" },
  { character: "🨜", name: "Black Chess Knight Rotated One Hundred Thirty-Five Degrees" },
  { character: "🨝", name: "Neutral Chess Knight Rotated One Hundred Thirty-Five Degrees" },
  { character: "🨞", name: "White Chess Turned King" },
  { character: "🨟", name: "White Chess Turned Queen" },
  { character: "🨠", name: "White Chess Turned Rook" },
  { character: "🨡", name: "White Chess Turned Bishop" },
  { character: "🨢", name: "White Chess Turned Knight" },
  { character: "🨣", name: "White Chess Turned Pawn" },
  { character: "🨤", name: "Black Chess Turned King" },
  { character: "🨥", name: "Black Chess Turned Queen" },
  { character: "🨦", name: "Black Chess Turned Rook" },
  { character: "🨧", name: "Black Chess Turned Bishop" },
  { character: "🨨", name: "Black Chess Turned Knight" },
  { character: "🨩", name: "Black Chess Turned Pawn" },
  { character: "🨪", name: "Neutral Chess Turned King" },
  { character: "🨫", name: "Neutral Chess Turned Queen" },
  { character: "🨬", name: "Neutral Chess Turned Rook" },
  { character: "🨭", name: "Neutral Chess Turned Bishop" },
  { character: "🨮", name: "Neutral Chess Turned Knight" },
  { character: "🨯", name: "Neutral Chess Turned Pawn" },
  { character: "🨰", name: "White Chess Knight Rotated Two Hundred Twenty-Five Degrees" },
  { character: "🨱", name: "Black Chess Knight Rotated Two Hundred Twenty-Five Degrees" },
  { character: "🨲", name: "Neutral Chess Knight Rotated Two Hundred Twenty-Five Degrees" },
  { character: "🨳", name: "White Chess King Rotated Two Hundred Seventy Degrees" },
  { character: "🨴", name: "White Chess Queen Rotated Two Hundred Seventy Degrees" },
  { character: "🨵", name: "White Chess Rook Rotated Two Hundred Seventy Degrees" },
  { character: "🨶", name: "White Chess Bishop Rotated Two Hundred Seventy Degrees" },
  { character: "🨷", name: "White Chess Knight Rotated Two Hundred Seventy Degrees" },
  { character: "🨸", name: "White Chess Pawn Rotated Two Hundred Seventy Degrees" },
  { character: "🨹", name: "Black Chess King Rotated Two Hundred Seventy Degrees" },
  { character: "🨺", name: "Black Chess Queen Rotated Two Hundred Seventy Degrees" },
  { character: "🨻", name: "Black Chess Rook Rotated Two Hundred Seventy Degrees" },
  { character: "🨼", name: "Black Chess Bishop Rotated Two Hundred Seventy Degrees" },
  { character: "🨽", name: "Black Chess Knight Rotated Two Hundred Seventy Degrees" },
  { character: "🨾", name: "Black Chess Pawn Rotated Two Hundred Seventy Degrees" },
  { character: "🨿", name: "Neutral Chess King Rotated Two Hundred Seventy Degrees" },
  { character: "🩀", name: "Neutral Chess Queen Rotated Two Hundred Seventy Degrees" },
  { character: "🩁", name: "Neutral Chess Rook Rotated Two Hundred Seventy Degrees" },
  { character: "🩂", name: "Neutral Chess Bishop Rotated Two Hundred Seventy Degrees" },
  { character: "🩃", name: "Neutral Chess Knight Rotated Two Hundred Seventy Degrees" },
  { character: "🩄", name: "Neutral Chess Pawn Rotated Two Hundred Seventy Degrees" },
  { character: "🩅", name: "White Chess Knight Rotated Three Hundred Fifteen Degrees" },
  { character: "🩆", name: "Black Chess Knight Rotated Three Hundred Fifteen Degrees" },
  { character: "🩇", name: "Neutral Chess Knight Rotated Three Hundred Fifteen Degrees" },
  { character: "🩈", name: "White Chess Equihopper" },
  { character: "🩉", name: "Black Chess Equihopper" },
  { character: "🩊", name: "Neutral Chess Equihopper" },
  { character: "🩋", name: "White Chess Equihopper Rotated Ninety Degrees" },
  { character: "🩌", name: "Black Chess Equihopper Rotated Ninety Degrees" },
  { character: "🩍", name: "Neutral Chess Equihopper Rotated Ninety Degrees" },
  { character: "🩎", name: "White Chess Knight-Queen" },
  { character: "🩏", name: "White Chess Knight-Rook" },
  { character: "🩐", name: "White Chess Knight-Bishop" },
  { character: "🩑", name: "Black Chess Knight-Queen" },
  { character: "🩒", name: "Black Chess Knight-Rook" },
  { character: "🩓", name: "Black Chess Knight-Bishop" },
  { character: "🩠", name: "Xiangqi Red General" },
  { character: "🩡", name: "Xiangqi Red Mandarin" },
  { character: "🩢", name: "Xiangqi Red Elephant" },
  { character: "🩣", name: "Xiangqi Red Horse" },
  { character: "🩤", name: "Xiangqi Red Chariot" },
  { character: "🩥", name: "Xiangqi Red Cannon" },
  { character: "🩦", name: "Xiangqi Red Soldier" },
  { character: "🩧", name: "Xiangqi Black General" },
  { character: "🩨", name: "Xiangqi Black Mandarin" },
  { character: "🩩", name: "Xiangqi Black Elephant" },
  { character: "🩪", name: "Xiangqi Black Horse" },
  { character: "🩫", name: "Xiangqi Black Chariot" },
  { character: "🩬", name: "Xiangqi Black Cannon" },
  { character: "🩭", name: "Xiangqi Black Soldier" },
  { character: "🩰", name: "Ballet Shoes" },
  { character: "🩱", name: "One-Piece Swimsuit" },
  { character: "🩲", name: "Briefs" },
  { character: "🩳", name: "Shorts" },
  { character: "🩴", name: "Thong Sandal" },
  { character: "🩵", name: "Light Blue Heart" },
  { character: "🩶", name: "Grey Heart" },
  { character: "🩷", name: "Pink Heart" },
  { character: "🩸", name: "Drop Of Blood" },
  { character: "🩹", name: "Adhesive Bandage" },
  { character: "🩺", name: "Stethoscope" },
  { character: "🩻", name: "X-Ray" },
  { character: "🩼", name: "Crutch" },
  { character: "🪀", name: "Yo-Yo" },
  { character: "🪁", name: "Kite" },
  { character: "🪂", name: "Parachute" },
  { character: "🪃", name: "Boomerang" },
  { character: "🪄", name: "Magic Wand" },
  { character: "🪅", name: "Pinata" },
  { character: "🪆", name: "Nesting Dolls" },
  { character: "🪇", name: "Maracas" },
  { character: "🪈", name: "Flute" },
  { character: "🪐", name: "Ringed Planet" },
  { character: "🪑", name: "Chair" },
  { character: "🪒", name: "Razor" },
  { character: "🪓", name: "Axe" },
  { character: "🪔", name: "Diya Lamp" },
  { character: "🪕", name: "Banjo" },
  { character: "🪖", name: "Military Helmet" },
  { character: "🪗", name: "Accordion" },
  { character: "🪘", name: "Long Drum" },
  { character: "🪙", name: "Coin" },
  { character: "🪚", name: "Carpentry Saw" },
  { character: "🪛", name: "Screwdriver" },
  { character: "🪜", name: "Ladder" },
  { character: "🪝", name: "Hook" },
  { character: "🪞", name: "Mirror" },
  { character: "🪟", name: "Window" },
  { character: "🪠", name: "Plunger" },
  { character: "🪡", name: "Sewing Needle" },
  { character: "🪢", name: "Knot" },
  { character: "🪣", name: "Bucket" },
  { character: "🪤", name: "Mouse Trap" },
  { character: "🪥", name: "Toothbrush" },
  { character: "🪦", name: "Headstone" },
  { character: "🪧", name: "Placard" },
  { character: "🪨", name: "Rock" },
  { character: "🪩", name: "Mirror Ball" },
  { character: "🪪", name: "Identification Card" },
  { character: "🪫", name: "Low Battery" },
  { character: "🪬", name: "Hamsa" },
  { character: "🪭", name: "Folding Hand Fan" },
  { character: "🪮", name: "Hair Pick" },
  { character: "🪯", name: "Khanda" },
  { character: "🪰", name: "Fly" },
  { character: "🪱", name: "Worm" },
  { character: "🪲", name: "Beetle" },
  { character: "🪳", name: "Cockroach" },
  { character: "🪴", name: "Potted Plant" },
  { character: "🪵", name: "Wood" },
  { character: "🪶", name: "Feather" },
  { character: "🪷", name: "Lotus" },
  { character: "🪸", name: "Coral" },
  { character: "🪹", name: "Empty Nest" },
  { character: "🪺", name: "Nest With Eggs" },
  { character: "🪻", name: "Hyacinth" },
  { character: "🪼", name: "Jellyfish" },
  { character: "🪽", name: "Wing" },
  { character: "🪿", name: "Goose" },
  { character: "🫀", name: "Anatomical Heart" },
  { character: "🫁", name: "Lungs" },
  { character: "🫂", name: "People Hugging" },
  { character: "🫃", name: "Pregnant Man" },
  { character: "🫄", name: "Pregnant Person" },
  { character: "🫅", name: "Person With Crown" },
  { character: "🫎", name: "Moose" },
  { character: "🫏", name: "Donkey" },
  { character: "🫐", name: "Blueberries" },
  { character: "🫑", name: "Bell Pepper" },
  { character: "🫒", name: "Olive" },
  { character: "🫓", name: "Flatbread" },
  { character: "🫔", name: "Tamale" },
  { character: "🫕", name: "Fondue" },
  { character: "🫖", name: "Teapot" },
  { character: "🫗", name: "Pouring Liquid" },
  { character: "🫘", name: "Beans" },
  { character: "🫙", name: "Jar" },
  { character: "🫚", name: "Ginger Root" },
  { character: "🫛", name: "Pea Pod" },
  { character: "🫠", name: "Melting Face" },
  { character: "🫡", name: "Saluting Face" },
  { character: "🫢", name: "Face With Open Eyes And Hand Over Mouth" },
  { character: "🫣", name: "Face With Peeking Eye" },
  { character: "🫤", name: "Face With Diagonal Mouth" },
  { character: "🫥", name: "Dotted Line Face" },
  { character: "🫦", name: "Biting Lip" },
  { character: "🫧", name: "Bubbles" },
  { character: "🫨", name: "Shaking Face" },
  { character: "🫰", name: "Hand With Index Finger And Thumb Crossed" },
  { character: "🫱", name: "Rightwards Hand" },
  { character: "🫲", name: "Leftwards Hand" },
  { character: "🫳", name: "Palm Down Hand" },
  { character: "🫴", name: "Palm Up Hand" },
  { character: "🫵", name: "Index Pointing At The Viewer" },
  { character: "🫶", name: "Heart Hands" },
  { character: "🫷", name: "Leftwards Pushing Hand" },
  { character: "🫸", name: "Rightwards Pushing Hand" },
];
